//
//  NPRDataKey.swift
//  NPR_census
//
//  Created by Dileep on 28/08/20.
//  Copyright © 2020 admin. All rights reserved.
//

import UIKit


/*
struct NPRDataKey {
    
//    var aadhar = "aadhar"
////    init() {
////       aadhar = "aadhar"
////    }
//    
/
//     var address_line2 = "address_line2"
//      let address_line2_sl = "address_line2_sl"
//     let address_line3_sl = "address_line3_sl"
//    static let address_line4_sl  = "address_line4_sl"
//    static let address_line5_sl = "address_line5_sl"
//    static let address_state = "address_state"
//    static let address_subDistrict = "address_subDistrict"
//  static let addressCountry_sl = "addressCountry_sl"
//    static let  age = "age"
//    static let available = "available"
//    static let birth_country_sl = "birth_country_sl"
//   static let birth_district_sl = "birth_district_sl"
//    static let birth_state_sl = "birth_state_sl"
//    static let birthAddress = "birthAddress"
//    static let birthCountryCode = "birthCountryCode"
//    static let birthCountryName = "birthCountryName"
//   static let birthDistrictCode = "birthDistrictCode"
//    static let birthStateCode = "birthStateCode"
//   static let birthStateName = "birthStateName"
//    static let birthVillageName = "birthVillageName"
//    static let bithDistrictName = ""
//    static let block_no = "block_no"
//   static let censusHH_number = "censusHH_number"
//    static let censusHouse_number = "censusHouse_number"
//    static let count_formNumber = "count_formNumber"
//    static let countryName_sl = "countryName_sl"
//    static let dbFile_name = "dbFile_name"
//    static let died = "died"
//    static let districtName_sl = "districtName_sl"
//    static let dob = "dob"
//    static let dob_type = "dob_type"
//    static let document1 = "document1"
//    static let document2 = "document2"
//    static let document3 = "document3"
//    static let document4 = "document4"
//    static let driving_lincence = "driving_lincence"
//    static let duration_inYear = "duration_inYear"
//    static let edu_code = "edu_code"
//    static let eduName_sl = "eduName_sl"
//    static let enumerated_on = "enumerated_on"
//    static let enumerator = "enumerator"
//    static let extra_24 = "extra_24"
//    static let extra_25 = "extra_25"
//    static let extra_26 = "extra_26"
//    static let extra_27 = "extra_27"
//    static let extra_28 = "extra_28"
//    static let extra_29 = "extra_29"
//    static let extra17 = "extra17"
//    static let extra18 = "extra18"
//    static let extra19 = "extra19"
//    static let extra20 = "extra20"
//    static let father_code = "father_code"
//    static let father_dob = "father_dob"
//    static let father_dobType = "father_dobType"
//    static let father_name = "father_name"
//    static let fatherBirth_country_sl = "fatherBirth_country_sl"
//    static let fatherBirth_district_sl = "fatherBirth_district_sl"
//    static let fatherBirth_state_sl = "fatherBirth_state_sl"
//    static let fatherBirthCountry = "fatherBirthCountry"
//    static let fatherBirthPlace = "fatherBirthPlace"
//    static let fatherBirthState = "fatherBirthState"
//    static let fatherName_sl = "fatherName_sl"
//    static let form_number = "form_number"
//    static let gender_id = "gender_id"
//    static let genderID_enu = "genderID_enu"
//    static let hh_status = "hh_status"
//    static let hh_type = "hh_type"
//    static let id = "id"
//    static let imei = "imei"
//    static let institution_name = "institution_name"
//    static let institution_name_sl = "institution_name_sl"
//    static let ipAddress = "ipAddress"
//    static let is_signUpdated = "is_signUpdated"
//    static let isStarted = "isStarted"
//    static let last_resident_country_sl = "last_resident_country_sl"
//    static let last_resident_district_sl = "last_resident_district_sl"
//    static let last_resident_state_sl = "last_resident_state_sl"
//    static let lastResidencyCountry = "lastResidencyCountry"
//    static let lastResidencyDistrict = "lastResidencyDistrict"
//    static let lastResidencyState = "lastResidencyState"
//    static let latest_master = "latest_master"
//    static let lattitude = "lattitude"
//    static let longitute = "longitute"
//    static let m_id = "m_id"
//    static let marital_status = "marital_status"
//    static let memberStatus = "memberStatus"
//    static let memberStatus_prev_exercise = "memberStatus_prev_exercise"
//    static let migrated = "migrated"
//    static let mobile = "mobile"
//    static let mother_birthCountry = "mother_birthCountry"
//    static let mother_birthDistrict = "mother_birthDistrict"
//    static let mother_birthPlace = "mother_birthPlace"
//    static let mother_birthState = "mother_birthState"
//    static let mother_code = "mother_birthState"
//    static let mother_dob = "mother_dob"
//    static let mother_dobType = "mother_dobType"
//    static let motherBirth_country_sl = "motherBirth_country_sl"
//    static let motherBirth_district_sl = "motherBirth_district_sl"
//    static let motherBirth_state_sl = "motherBirth_state_sl"
//    static let motherName = "motherName"
//    static let motherName_sl = "motherName_sl"
//    static let motherTounge = "motherTounge"
//    static let name = "name"
//    static let name_instant_langauge = "name_instant_langauge"
//    static let name_on_cardSL = "name_on_cardSL"
//    static let name_responded = "name_responded"
//    static let nameSL = "nameSL"
//    static let nationality = "nationality"
//    static let nationality_sl = "nationality_sl"
//    static let new_tin = "new_tin"
//    static let occu_code = "occu_code"
//    static let occuName = "occuName"
//    static let old_tin = "old_tin"
//    static let otherMotherTounge = "otherMotherTounge"
//    static let paddre_district = "paddre_district"
//    static let paddre_line1 = "paddre_line1"
//    static let paddre_line2 = "paddre_line2"
//    static let paddre_tahsil = "paddre_tahsil"
//    static let paddress_block_code = "paddress_block_code"
//    static let paddress_country = "paddress_country"
//    static let paddress_line2 = "paddress_line2"
//    static let paddress_state = "paddress_state"
//    static let paddress_town = "paddress_town"
//    static let panCard_number = "panCard_number"
//    static let passpord_id = "passpord_id"
//    static let phone_responded = "phone_responded"
//    static let pinCode = "pinCode"
//    static let ppinCode = "ppinCode"
//    static let primaryLangauge = "primaryLangauge"
//    static let rationCard_number = "rationCard_number"
//    static let rel_code = "rel_code"
//    static let relNameSL = "relNameSL"
//    static let resident_id = "resident_id"
//    static let secondaryLangauge = "secondaryLangauge"
//    static let selfEnumerationRef_number = "selfEnumerationRef_number"
//    static let sign_by_enum_onBehalf_of_responded = "sign_by_enum_onBehalf_of_responded"
//    static let sign_responded = "sign_responded"
//    static let slNo_responded = "slNo_responded"
//    static let sloHHD = "sloHHD"
//    static let sloMember = "sloMember"
//    static let sper_is_HH_completed = "sper_is_HH_completed"
//    static let sper_sync_on = "sper_sync_on"
//    static let splitFrom = "splitFrom"
//    static let splitInto = "splitInto"
//    static let spouseBirthPlace = "spouseBirthPlace"
//    static let spouseCode = "spouseCode"
//    static let spouseName = "spouseName"
//    static let spouseName_sl = "spouseName_sl"
//    static let stateName_sl = "stateName_sl"
//    static let staying_since_birthdate = "staying_since_birthdate"
//    static let sub_eb = "sub_eb"
//    static let super_ok = "super_ok"
//    static let super_remark = "super_remark"
//    static let super_remark_on = "super_remark_on"
//    static let superVisor = "superVisor"
//    static let tin = "tin"
//    static let uploded_by = "uploded_by"
//    static let userID = "userID"
//    static let villageName_sl = "villageName_sl"
//    static let voter_id = "voter_id"
//    
}
*/
