# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NPR-2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  
  
  
  
end
