//
//  English.swift
//  NPR-2020
//
//  Created by IOS Development Team on 27/01/21.
//  Copyright © 2021 admin. All rights reserved.
//

import Foundation

class EnglishLang: Encodable {
    
    public var validation_staying_at_present_address_years_not = "Staying at present address can not be 0."
    public var eb_removed = "\"\"This HLB is not assigned to you. Please check with your Supervisor.\"\""
    public var eb_update = "HLB syncronized Succesfully"
    public var expected_hh_can_not_be_blank = "Expected Households No. can not be blank"
    public var expected_hh_can_not_be_one = "Expected Households No. can not be 1."
    public var age_text = "Enter approx age to calculate date of birth"
    public var expected_hh_can_not_be_more_than = "Expected Households No. can not be exceed than no.of HouseHold Members"
    public var alert_date = " Member not sure about year of birth but knows approximate age."
    public var success = "Data Uploaded Successfully."
    public var error401 = "You are not authorised user to upload Data."
    public var error400 = "Bad Request."
    public var error204 = "This HLB is not started by Enuemerator."
    public var fail = "Failed to upload data,try again."
    public var norecord = "You have no records to upload."
    public var nprstarted = "NPR block marked successfully."
    public var ebstartdateMark = "HLB Start Date Marked successFully"
    public var eb_complete_successfully = "HLB Complete successfully"
    public var button_yes = "Yes"
    public var button_no = "No"
    public var ebStartDate = "Unable to Fetch HLB Start Date . Please try again "
    public var searchHeading = "Total HouseHold in  HLB - "
    public var app_name = "NPR-2020"
    public var national_population_register = "National Population Register"
    public var developer_by = "Developed and Managed By"
    public var indian_gov = "ORGI, MHA, Government of India"
    public var version = "Version 1.1.1"
    public var please_wait = "Please Wait"
    public var loading_data = "Loading data..."
    public var wrong_password = "Please enter valid credential"
    public var user_id_password_cant_be_empty = "UserId and Password can not be empty."
    public var connected_to_internet = "Good! Connected to the Internet"
    public var not_connected_to_internet = "Sorry! Not connected to the internet"
    public var total_records = "Total Records - "
    public var total_households = "Total Households - "
    public var enter_eb_search = "Enter HLB for search"
    public var select_any_search_type = "Select any search type"
    public var enter_search_value = "Enter search value"
    public var new_hh_added = "New Member and Household Inserted Successfully.Now add another member in the same HouseHold."
    public var do_you_want_to_continue = "Do you want to continue?"
    public var yes_to_add_more_member = "Press YES to add more member, else click No."
    public var choose_any_member_to_mark_as_head = "Choose any member to mark them as HEAD."
    public var click_yes_to_mark_as_head = "To mark selected member as the Head,click YES to continue else click NO."
    public var member_updated_successfully = "Member updated successfully"
    public var new_member_added_successfully = "New member added successfully. Now add another member in the same HouseHold."
    public var sign_by_enumerator_on_behalf_of = "Signed By Enumerator on behalf of  "
    public var sign_by = "Signed by- "
    public var please_tick_the_consent = "Please tick the consent."
    public var choose_respondent = "Choose Respondent"
    public var hh_no = "Household No.- "
    public var block_no = "Block No.- "
    public var total_members = "Total Members- "
    public var signature_capture_successful = "Signature capture successful."
    public var signature_capturing_cancelled = "Signature capture unsuccessful."
    public var failed_to_upload_file_check_your_internet_connection = "Failed to upload file.Please check your internet connection."
    public var file_upload_successfully = "File uploaded successfully."
    public var eb_doesnot_completed_try_again = "HLB doesn\'t completed,try again upload to Complete HLB - "
    public var failed_to_upload_file = "Failed to upload File- "
    public var connected_network_is_slow_try_again = "Connected network is slow.Please try again later."
    public var user_doesnot_exist = "User doesn\'t exist"
    public var downloading_data = "Downloading Data..."
    public var processing_please_wait = "Processing, please wait..."
    public var eb_already_downloaded = "HLB already DOWNLOADED."
    public var please_download_eb_to_continue = "Please download HLB to continue."
    public var failed_to_download_file_please_check_internet = "Failed to download file.Please check your internet connection."
    public var failed_to_download_file = "Failed to download file.- "
    public var eb_download_successfully = "HLB DOWNLOADED successfully "
    public var eb_canot_be_download_try_again = "HLB can\'t be download.Try again... "
    public var progress_ = "Progress: "
    public var downloaded_at = "Downloaded at: "
    public var error = "Error: "
    public var something_went_wrong = "Something went wrong."
    public var old = "NPR HH No.- "
    public var new_hh = "Census HH No - "
    public var due_to_hh_not_available = " due to household not available"
    public var due_to_family_migrated = " due to family migrated"
    public var select_any_option_to_skip = "Select any option to skip"
    public var sr_no_ = "Sr.No.-"
    public var resend_otp = "RESEND OTP"
    public var verify_otp_lable = "VERIFY OTP"
    public var clear = "Clear"
    public var save = "Save"
    public var skip = "SKIP"
    public var select_mother_tounge = "Select Mother Tongue"
    public var validation_mother_tounge = "Choose Mother Tongue"
    public var mother_tounge = "Mother Tongue"
    public var same_as_present_address = "Permanent Address same as Present Address"
    public var split = "Split"
    public var expected_hh_to_split = "Enter number of household to split the selected household"
    public var hh_spiliting = "Household Splitting"
    public var hh_split_skip = "None Household will split."
    public var selected_members_will_remain_in_hh = "Select members which will remain in household no.-"
    public var due_to_hh_not_available_ = " due to household not available?"
    public var due_to_family_migrated_ = " due to family migrated?"
    public var due_to_hh_locked = " due to household locked"
    public var due_to_hh_locked_ = " due to household locked?"
    public var login = "Login"
    public var supervisor_login_title = "Supervisor Login"
    public var userid = "User Id"
    public var password = "Password"
    public var LOGIN = "SIGN IN"
    public var sup_logout = "LOGOUT"
    public var select_eb = "Select any HLB"
    public var not_downloaded = "Not Downloaded"
    public var downloaded = "Downloaded"
    public var eb_proceed_comfirmation = "Are you sure to continue with the following details?"
    public var state = "State"
    public var district = "District"
    public var sub_district = "Sub District"
    public var town_village = "Town/Village"
    public var ward = "Ward"
    public var block = "Block"
    public var pincode = "Pincode"
    public var DISAGREE = "DISAGREE"
    public var AGREE = "AGREE"
    public var navigation_drawer_open = "Open navigation drawer"
    public var navigation_drawer_close = "Close navigation drawer"
    public var nav_header_title = "Android Studio"
    public var nav_header_subtitle = "android.studio@android.com"
    public var nav_header_desc = "Navigation header"
    public var action_settings = "Settings"
    public var enter_member_dob_first = "Firstly enter correct DOB of this member."
    public var menu_home = "Home"
    public var menu_gallery = "Gallery"
    public var menu_slideshow = "Slideshow"
    public var menu_tools = "Tools"
    public var menu_share = "Share"
    public var menu_send = "Send"
    public var location_particular = "Location Particular"
    public var hh_summary = "Incomplete HouseHold"
    public var upload_data = "Upload Data"
    public var search_edit = "View/Edit"
    public var sup_view = "Supervisor View"
    public var sup_ok = "OK"
    public var sup_remark = "REMARK"
    public var progress = "Progress"
    public var lp_headline = "You are working for the given Jurisdiction"
    public var status = "Status"
    public var census_house_no = "Census House No. as in Houselist"
    public var census_household_no = "Census Household no. as in Houselist (New)"
    public var name = "Name"
    public var first_name = "First Name"
    public var middle_name = "Middle Name"
    public var last_name = "Last Name"
    public var mobile = "Mobile"
    public var dob = "DOB"
    public var head = "Head"
    public var aadhaar = "Aadhaar"
    public var search = "Search"
    public var proceed = "Proceed"
    public var ad_new_hh = "Add New Household"
    public var assign_eb_number = "Assign HLB - "
    public var hh_number = "Household Number"
    public var hh_number2 = "NPR Household Number"
    public var head_of_family_name = "Name (Head of the Household)"
    public var head_of_family_first_name = "First Name(Head of the Household)"
    public var number_of_member_in_family  = ""
    public var hh_member_form = "Household Form"
    public var hh_member_updation_form = "Household Update Form"
    public var hh_member_addtion = "Household New Member Addition"
    public var member_added_sucess = "Member Added successfully."
    public var in_habitated_eb_completion = "Are you sure you want to submit this HLB as Uninhabited HLB ?"
    public var signature_captured_cancel = "Signature capture unsuccessful."
    public var signature_captured_successfull = "Signature captured successful."
    public var firstly_update_head_present_address_data = "Firstly update Head's Present Address."
    public var firstly_update_head_p_address_data = "Firstly update Head's Permanent Address."
    public var previous_memebr_details_not_complete = "Previous Member's Parents Data is not complete."
    public var selected_memebr_details_not_complete = "Selected Member's Details is not complete."
    public var select_father_name = "Select Father's name"
    public var select_mother_name = "Select Mother's name"
    public var personal_details = "Personal Details"
    public var same_as_head = "Permanent Address same as Head"
    public var same_as_head_present_address = "Present Address same as Head"
    public var parents_same_as_previous = "Parents Same as previous member of the same household"
    public var parents_are_in_hh = "Parents stay in this household"
    public var parents_details = "Parents Details"
    public var education_details = "Education/Occupation/Mother tongue"
    public var identification_details = "Identification Details"
    public var address = "Present Address Details"
    public var current_address = "Present Address"
    public var current_address_state = "State"
    public var current_address_district = "District"
    public var current_address_tehsil = "Sub-district"
    public var permanent_address_details = "Permanent Address Details"
    public var permanent_address = "Permanent Address Country"
    public var permanent_address2 = "Permanent Address State"
    public var permanent_address3 = "Permanent Address District"
    public var permanent_address4 = "Permanent Address Sub-district"
    public var permanent_address5 = "Permanent Address Town/Village"
    public var permanent_address6 = "Permanent Address House and Locality"
    public var permanent_address7 = "Permanent Address Pin Code"
    public var respondent_details = "Respondent Details"
    public var residential_status = "Residential Status"
    public var contact_to_your_supervisor = "It's important to agree on assigned HLB to do allotted work. If any issues please contact to your Supervisor/Charge Officer."
    public var account_is_not_of_enumerator = "Kindly use enumerator login credentials!"
    public var account_is_not_of_supervisor = "Kindly use supervisor login credentials!"
    public var actual = "Actual"
    public var intention = "Intention"
    public var Others = "Others"
    public var gender = "Sex"
    public var Male = "Male"
    public var Female = "Female"
    public var trans_gender = "Transgender person"
    public var date_of_birth = "Date of Birth(DD-MM-YYYY)"
    public var age = "Age"
    public var dob_type = "Date of birth Type"
    public var declared = "Declared"
    public var marital_status = "Marital Status"
    public var never_married = "Never Married"
    public var seprated = "Separated"
    public var married = "Currently Married"
    public var widowed = "Widowed"
    public var divorced = "Divorced"
    public var nationality = "Nationality"
    public var nationality_declaratation = "* Nationality recorded is as declared by the respondent. This does not confer any right to Indian Citizenship. "
    public var indian = "INDIAN"
    public var save_member_data = "SAVE MEMBER DATA"
    public var f_name = "Father's Name"
    public var m_name = "Mother's Name"
    public var s_name = "Spouse's Name"
    public var f_dob = "Father's Date of Birth"
    public var m_dob = "Mother's Date of Birth"
    public var s_dob = "Spouse's Date of Birth"
    public var f_birth_address = "Father's Birth Place Country"
    public var f_birth_address2 = "Father's Birth Place State"
    public var f_birth_address3 = "Father's Birth Place District"
    public var f_birth_state = "Father's Birth State"
    public var m_birth_address = "Mother's Birth Place Country"
    public var m_birth_address2 = "Mother's Birth Place State"
    public var m_birth_address3 = "Mother's Birth Place District"
    public var f_birth_district = "Father's Birth District"
    public var m_birth_district = "Mother's Birth District"
    public var s_birth_district = "Spouse's Birth District"
    public var f_birth_village = "Father's Birth Village/Town"
    public var m_birth_village = "Mother's Birth Village/Town"
    public var s_birth_village = "Spouse's Birth Village/Town"
    public var education = "Education Qualification"
    public var occupation = "Occupation"
    public var aadhaar_status = "Aadhaar Status"
    public var aadhaar_available = "Aadhaar Available"
    public var eid_available = "EID  Available"
    public var aadhaar_not_available = "Not Available"
    public var aadhaar_not_enrolled = "Not Enrolled"
    public var passport = "If holding Passport, then enter Passport Number"
    public var voter_id = "Voter ID Number"
    public var homeScreen = "Home"
    public var pan_card = "PAN Card Number"
    public var driving_licence = "Driving Licence Number"
    public var member_sr_no = "Member Sr. No. - "
    public var new_member = "New Member"
    public var wheater_staying_at_present_addres_since_birth = "Whether staying at present address since birth"
    public var years_of_staying = "Staying at present address(in years)"
    public var address1 = "House Number and Locality"
    public var no_of_hh = "Enter No. of Households"
    public var address2 = "Town/Village"
    public var respondent_mobile = "Respondent Mobile Number"
    public var respondent_name = "Respondent's Name"
    public var skip_title = "Select reason for skipping the household-"
    public var select_head_title = "Select New Head for this Household "
    public var select_sup_eb_title = "Choose any HLB "
    public var expected_hh = " Expected No.of Households"
    public var do_you_want_to_change_the_hh = "Do you want to change the Expected Households No?"
    public var expected_hh_message = "There is no previous data in assigned HLB"
    public var expected_hh_can_not_be_zero = " Expected Households No. can not be 0."
    public var expected_hh_can_not_be_zero_after_eb_upload = " Now you can not add new household in this HLB."
    public var enter_remarks = "Enter Remark"
    public var locked_house = "Locked House"
    public var refused_answer = "Refused to answer"
    public var not_found = "Not Available"
    public var family_migrated = "Household Migrated/Moved Out"
    public var house_demolished = "House Demolished"
    public var other = "Other"
    public var cancel = "CANCEL"
    public var ok = "OK"
    public var enter_reson_to_skip_household = "Enter Reason to Skip HouseHold"
    public var hh_member_details = "Household Member Details"
    public var add_member = "Add Member"
    public var refresh = "Refresh"
    public var name_of_person = "Name"
    public var relationship = "Relationship"
    public var sex = "Sex"
    public var birth_address1 = "Birth Place Country"
    public var birth_address2 = "Birth Place State"
    public var birth_address3 = "Birth Place District"
    public var birth_tehsil = "Birth Sub-district"
    public var birth_district = "Birth District"
    public var birth_state = "Birth State"
    public var current_house = "Present Address House and Locality"
    public var current_village = "Present Address Village"
    public var current_pincode = "Present Address Pin Code"
    public var current_state = "Present Address State"
    public var current_district = "Present Address District"
    public var current_sub_district = "Present Address Sub-district"
    public var father_birth_address = "Father's Birth Address Country"
    public var father_birth_address2 = "Father's Birth Address State"
    public var father_birth_address3 = "Father's Birth Address District"
    public var mother_birth_address = "Mother's Birth Address Country"
    public var mother_birth_address2 = "Mother's Birth Address State"
    public var mother_birth_address3 = "Mother's Birth Address District"
    public var place_of_last_residence = "Last Residence Country"
    public var place_of_last_residence2 = "Last Residence State"
    public var place_of_last_residence3 = "Last Residence District"
    public var member_available = "Available"
    public var member_migrated = "Moved"
    public var member_died = "Died"
    public var serial_number = "Serial No."
    public var available = "Available"
    public var dead = "Died"
    public var migrated_out = "Moved Out"
    public var not_available = "Not Available"
    public var locked = "Locked"
    public var new_ = "New"
    public var signature_required = "Respondent Sign required"
    public var press_ok_to_take_signature = "Press OK to take Respondent Signature."
    public var respondent_signature = "Respondent Signature"
    public var enumerator_signature = "Enumerator Signature"
    public var sup_signature = "Supervisor Signature"
    public var signature_consent = "I acknowledge and confirm that the Enumerator has shown/read all my household particulars recorded on the App(as told by me) and I declare that all the information provided by me is true to the best of my knowledge and belief."
    public var respondant_unable_to_sign_consent = "Read and signed in front of respondent by Enumerator because respondent is unable to sign."
    public var respondent = "Respondent"
    public var emulator_status = "Enumerator Status"
    public var next = "NEXT"
    public var total_assigned_eb = "Total HLB Assigned"
    public var uploaded_eb = "Total Uploaded HLB"
    public var pending_eb = "Total Pending HLB"
    public var current_eb_status = "Current HLB Status"
    public var eb_number = "HLB Number"
    public var household_status = "Household Status"
    public var total_original_household = "Total Original Household"
    public var total_available_households = "Total Available Households"
    public var total_migrated_hh = "Total Moved Households"
    public var total_locked_hh = "Total Locked Households"
    public var total_not_available_hh = "Total ‘Not Available’ Households"
    public var total_new_hh = "Total New Households"
    public var total_households_original_new = "Total Households (Original+New)"
    public var total_updated_households = "Total Updated Households"
    public var total_pending_households = "Total Pending Households"
    public var member_status = "Member Status"
    public var total_original_members = "Total Original Members"
    public var available_members = "Available Members"
    public var dead_member = "Died Members"
    public var migrated_member = "Moved Out Members"
    public var total_new_members = "Total New Members"
    public var total_updated_members = "Total Updated Members"
    public var total_members_original_new = "Total Members (Original+New)"
    public var members_yet_to_be_udated = "Members Yet to be updated"
    public var member_with_passport = "Members with Indian Passport"
    public var member_with_aadhaar = "Members with Aadhaar"
    public var members_with_mobile_number = "Members with Mobile Number"
    public var member_with_voterID = "Members with Voter ID"
    public var member_with_dl = "Members with Driving Licence"
    public var total_house_hold = "Total Household"
    public var total_old_hh = "Total Old Household"
    public var total_npr_member = "Total NPR Members"
    public var total_updated_npr_member = "Total Updated NPR Member"
    public var member_with_pancard = "Member with Pan Card"
    public var na_member = "Not Available Member"
    public var loced_member = "Locked Member"
    public var total_old_member = "Total Old Member"
    public var total_old_member_found = "Total Old Member Found"
    public var total_migrated_member = "Total Moved Member"
    public var total_new_member = "Total New Member"
    public var total_new_member_with_passport = "Total New Member with Passport"
    public var total_new_member_with_aadhaar = "Total New Member with Aadhaar"
    public var total_new_member_with_voterID = "Total New Member with VoterID"
    public var total_new_member_with_dl = "Total New Member with Driving Licence"
    public var total_new_member_with_pancard = "Total New Member with Pancard"
    public var pending_members = "Pending Members"
    public var total_members_found = "Total Members Found"
    public var choose_country = "Choose any Country"
    public var choose_state = "Choose any State"
    public var choose_Nationality = "Choose your Nationality"
    public var choose_district = "Choose any District"
    public var choose_tehsil = "Choose any Sub-District"
    public var choose_respondant = "Choose Respondent Name"
    public var yes = "Yes"
    public var no = "No"
    public var reload_master_directory = "Reload Master Directory"
    public var sup_remark_length = "Failed to capture remark.Remark should be at least 3 characters long."
    public var submit = "SUBMIT"
    public var button_save = "SAVE"
    public var button_update = "UPDATE"
    public var button_add_member = "Add Member"
    public var hh_skipped = "Successfully skipped household number - "
    public var member_migrated_successfully = "Successfully Marked as Moved to Member number - "
    public var member_dead_successfully = "Successfully Marked as Died to Member number - "
    public var are_you_sure = "Are You Sure"
    public var to_exit_from_app = "To logout from Supervisor?"
    public var alert = "Alert"
    public var eb_completion_alert1 = "As pre data is completed,do you want to mark this HLB as completed?"
    public var eb_completion_alert2_title = "Are you sure to mark the current HLB completed?"
    public var eb_completion_alert2 = "If you click YES,then this HLB will be marked as Completed. Else,click NO."
    public var enumerator_sign = "Enumerator Sign below"
    public var sup_sign = "Supervisor Sign below..."
    public var to_skip_hh = "To skip Household Number -  "
    public var to_mark_member = "To mark Member  "
    public var as_migrated = " as Moved out"
    public var as_dead = " as Died"
    public var are_you_sure_to_exit_from_hh_form = "Are you sure you want to go back?"
    public var due_to_locked = " due to Locked?"
    public var are_you_sure_to_exit = "Are you sure you want to exit from the app?"
    public var you_will_loss_data = "If you press OK, you will lose entered data (if any)"
    public var user_does_not_exist = "User does not exist."
    public var please_check_your_internet_connection = "Please check your internet connection"
    public var wrong_login_type = "You are using wrong Login Type."
    public var no_imei_or_logintype_passed = "No IMEI or Login Type Passed"
    public var imei_exist = "To logout your account from previous Sign In device ?"
    public var cancel_hit = "Request Cancelled"
    public var verify_otp = "OTP Verification"
    public var otp_send_on = "OTP has been sent to - "
    public var please_enter_correct_otp = "Please enter correct OTP."
    public var signin_sucess = "Sign In Success"
    public var signin_sucess_in_another_device = "Sign In successful in this Device, and old device de-registered.."
    public var eb_not_alloted = "HLB not yet allotted to this user."
    public var upload_eb = "Upload Data"
    public var uploaded = "Uploaded"
    public var resend_otp_success = "Resend OTP successfully."
    public var forgot_password = "Forgot Password"
    public var supervisor_login = "Supervisor Login"
    public var registered_userId = "Registered User ID"
    public var new_password = "New Password"
    public var retype_password = "Retype Password"
    public var chnage_password_via_otp = "Change Password via OTP"
    public var CHANGE_PASSWORD = "CHANGE PASSWORD"
    public var password_field_can_not_be_blank = "Password fields can not be blank"
    public var both_password_should_be_same = "Both password should be same."
    public var password_chnaged = "Password Changed"
    public var please_login_again = "Please Login again with new password."
    public var no_member_to_make_head = "There is no member present in this household except head. So, you can not change Head this time. Click on CANCEL to EXIT."
    public var no_eb_to_choose_for_this_sup = "No HLB of this Enumerator are allotted to you for supervision."
    public var do_you_want_to_upload_locked_hh_also1 = "There are "
    public var do_you_want_to_upload_locked_hh_also2 = "locked household in this UPLOAD.Do you want to upload locked household? Click YES to upload them else click NO(will upload all completed records except Locked household)."
    public var eb_mark_as_completed = "HLB Completed Successfully."
    public var device_is_de_registered_so_not_allowed_yo_upload = "You are not allow to upload from this de-registered device."
    public var validation_census_house_no = "Check Census House Number as in Houselist, which can not be empty"
    public var validation_census_house_no_zero = "Census House Number can not be zero."
    public var validation_new_census_household_no_zero = "Census Household No. can not be zero."
    public var you_have_complted_10_hh_please_upload = "You have completed 10 households but not synced them. Please sync now to avoid data loss."
    public var you_have_complted_50_member_please_upload = "You have completed 50 members but not synced them. Please sync now to avoid data loss."
    public var validation_new_census_household_no = "Check Census Household No. as in Houselist(New)"
    public var validation_name = "Name should be at least 3 characters long"
    public var validation_first_name = "First Name should be at least 2 characters long"
    public var validation_first_name_startwith = "First Name should start with character only."
    public var validation_middle_name = "Middle Name should be at least 2 characters long"
    public var validation_middle_name_startwith = "Middle Name should start with character only."
    public var validation_last_name = "Last Name should be at least 2 characters long"
    public var validation_last_name_startwith = "Last Name should start with character only."
    public var validation_hh_no = "Household No. should be valid number."
    public var validation_hh_no_already_exist = "Household No. already exist"
    public var validation_newchh_no_already_exist = "Census Household no. as in Houselist (New) already exist"
    public var validation_hh_family_membr_no = "No. of family Member should be valid number."
    public var validation_relationship = "Choose relationship with Head."
    public var validation_nationality = "Nationality should be at least of 3 characters long"
    public var feild_should_not = "Field should not be blank"
    public var validation_gender = "Choose Sex"
    public var validation_marital_status = "Choose Marital Status"
    public var validation_member_dob = "Member's date of birth can not be empty"
    public var validation_member_dob_not_valid = "Please enter a valid Member's date of birth."
    public var validation_dob_date_today_date = "Birth Date can not be today's date"
    public var validation_dob_date_future_date = "Birth Date can not be future date"
    public var validation_member_birthcountry = "Choose Birth Country"
    public var validation_member_birthstate = "Choose Birth State"
    public var validation_member_birthdistrict = "Choose Birth District"
    public var validation_member_Nationality = "Choose your Country"
    public var validation_member_birthtehsil = "Choose Birth Sub-District"
    public var validation_education = "Choose Education Qualification"
    public var validation_occupation = "Choose Occupation"
    public var validation_present_state = "Choose Present Address State"
    public var validation_present_district = "Choose Present Address District"
    public var validation_present_sub_district = "Choose Present Address Sub-District"
    public var validation_present_address1 = "Check Present Address House Number and Locality"
    public var validation_present_address2 = "Check Present Address Town/Village"
    public var validation_present_pincode = "Check Present Address Pin Code"
    public var validation_permaneent_country = "Choose Permanent Address Country"
    public var validation_permaneent_state = "Choose Permanent Address State"
    public var validation_permaneent_district = "Choose Permanent Address District"
    public var validation_permaneent_tehsil = "Choose Permanent Address Sub-District"
    public var validation_permaneent_address1 = "Check House Number and Locality"
    public var validation_permaneent_address2 = "Check Town/Village"
    public var validation_permaneent_pincode = "Check Permanent Address Pin Code"
    public var validation_staying_at_present_address_yes_no = "Choose Whether staying at present address since birth."
    public var validation_staying_at_present_address_years = "Staying at present address can not be empty."
    public var validation_staying_at_present_address_years_can_not_be_more_than_age = "This value can not be more than your age."
    public var validation_staying_at_present_address_years_invalid = "Staying at present address can not be greater than member's age"
    public var validation_last_residence_country = "Choose Last Residence Address Country."
    public var validation_last_residence_state = "Choose Last Residence Address State."
    public var validation_last_residence_district = "Choose Last Residence Address District."
    public var validation_father_name = "Father's name should be at least 3 characters long."
    public var validation_father_dob = "Father's DOB can not be empty"
    public var validation_father_dob_today_date = "Father's DOB can not be today's date"
    public var validation_father_dob_future_date = "Father's DOB can not be future date"
    public var validation_mother_dob_not_valid = "Please enter a valid Mother's date of birth."
    public var validation_father_dob_not_valid = "Please enter a valid Father's date of birth."
    public var validation_father_dob_with_member_same = "Father's DOB can not be same as Member's DOB."
    public var validation_father_birth_country = "Choose Father's Birth Country."
    public var validation_father_birth_state = "Choose Father's Birth State."
    public var validation_father_birth_district = "Choose Father's Birth District."
    public var validation_mother_name = "Mother's name should be at least 3 characters long."
    public var validation_mother_dob = "Mother's DOB can not be empty."
    public var validation_mother_birth_country = "Choose Mother's Birth Country."
    public var validation_mother_birth_state = "Choose Mother's Birth State."
    public var validation_mother_birth_district = "Choose Mother's Birth District."
    public var validation_spouse_name = "Spouse's name should be at least 3 characters long."
    public var validation_aadhaar = "Please enter a valid Aadhaar number."
    public var validation_mobile = "Please check Mobile number."
    public var validation_passport = "Please check Passport number."
    public var validation_voterid = "Please check Voter ID number."
    public var validation_pan_card = "Please enter a valid Pan Card number"
    public var validation_dl = "Please check Driving License Number"
    public var validation_respondent_name = "Respondent's Name should be at least 3 characters long."
    public var validation_respondent_mobile = "Please check respondent mobile number."
    public var validation_spouse_name_blank = "Spouse's name can not be left blank."
    public var data_clear_open_app_again = "App data cleared; open app again..."
    public var shift = "Shift"
    public var to_shift = "To shift"
    public var select_hh_for_member_shifting = "Select HouseHold to shift selected member"
    public var choose_any_hh_to_shift_member = "Choose any household to shift selected member"
    public var db_reload = "After you press OK, the current data will be deleted and the last synced data will be added."
    public var selected_members_are = "Selected Members are = "
    public var remaning_members = "Remaining Members = "
    public var select_any_member_to_split = "Please select any member first to split."
    public var spliting_completed = "Splitting completed"
    public var first_member_sr_no = "00001"
    public var first_hh_no = "00001"
    public var failed_to_download_file_no_data_found = "No data found for this HLB "
    public var recovery = "Recovery"
    public var hh_type = "Type of Household"
    public var normal = "Normal"
    public var institutional = "Institutional"
    public var houseless = "Houseless"
    public var check_hh_type = "Please choose Type of Household"
    public var name_of_institue = "Name of Institution"
    public var validation_name_of_institution = "Please enter Institutional Name"
    public var delete = "Delete"
    public var to_delete = "To delete Member -"
    public var to_delete_hh = "To delete Household No -"
    public var head_delete_message = "You can not delete Head. If you want to delete this member,then firstly change the head."
    public var member_deleted_sucess_message1 = "Member number -"
    public var member_deleted_sucess_message2 = "deleted successfully."
    public var self_enu_ref_no = "SE Reference Number"
    public var enter_mother_tounge = "Enter Mother Tongue"
    public var validation_mother_tounge_1 = "Enter valid Mother Tongue"
    public var other_mother_tongue = "Other Mother"
    public var error_wile_connecting_to_server = "Error while connecting to server"
    public var connecting_to_server = "Connecting to server"
    public var downloading_required_data = "Downloading the required resources."
    public var activated_devic_title = "You already have an active device."
    public var same_device_already_activated = "Your account is already activated. Would you like to de-enroll and proceed on this device? If Yes, then the data which is not uploaded will not be seen on the new device."
    public var switch_eb = "Switch HLB"
    public var no_eb = "There is no HLB allotted to you."
    public var language_error = "You have chosen English as your priority. Please change your keyboard settings to English."
    public var no_data = "No data"
    public var search_dob = "Search using DOB"
    public var search_aadhaar = "Search using Aadhaar"
    public var search_name = "Search using Name"
    public var search_head = "Search using Head of HH"
    public var search_mobile = "Search using Mobile Number"
    public var enter_search_name = "Please enter Name"
    public var enter_search_dob = "Please enter DOB"
    public var enter_search_aadhaar = "Please enter Aadhaar"
    public var enter_search_head = "Please enter Head Name"
    public var enter_search_mobile = "Please enter Mobile"
    public var select_any_option_to_search = "Please select any option first to search"
    public var search_head_name_from_hlo = "Search head name from HLO"
    public var aadhar_detail_alert = "Do you want to proceed without adding Aadhaar detail?"
    public var relationship_with_head = "Relationship with Head"
    public var permanent_address_same_as_member = "Permanent Address Same as "
    public var country = "Country"
    public var choose_member = "Choose member"
    public var de_enroll_message1 = "\"This User Is Already Active on - \""
    public var de_enroll_message2 = "\" . Please Sync The Data From That Device, Before Registering This Device, Otherwise The Data Stored In Other Device Will Be Lost.\""
    public var census_housing_number = "\"Census House Number- \""
    public var census_house_hold_number = "\"Census House Hold Number- \""
    public var search_for_mother_tongue = "Type other, if unable to find your mother tongue"
    public var loading = "Loading..."
    public var field_should_not_be_blank = "Field should not be blank"
    public var validation_age = "Entered age should be less than or equal to 125"
    public var user_not_enrolled_for_mobile_application = "User not enrolled for Mobile application"
    public var email_id_not_available = "\" & Email id is not available.\""
    public var server_error = "Server Error"
    public var unauthorized_access = "Unauthorized Access"
    public var invalid_otp = "Invalid OTP"
    public var required_resources_downloaded_successfully = "Required resources downloaded Successfully."
    public var cancel_lower = "Cancel"
    public var OK = "OK"
    public var restart = "Restart"
    public var server_connection_issue = "Server connection Issue - "
    public var connection_failed_due_to = "Connection failed due to - "
    public var failed = "Failed"
    public var mother_tongue_already_present = "Please select mother tongue from the list"
    public var no_data_to_upload = "No data to Upload in this HLB"
    public var initializing_please_wait = "Initializing..."
    public var retry_upload = "Unable to connect with server, please try again."
    public var upload_from_previous_device = "Please upload from previously registered device."
    public var validation_both_password_length = "Both password should be at least 6 characters long."
    public var already_marked_as_complted_and_uninhabited = "This HLB is already marked as Completed and Uninhabited."
    public var already_marked_as_complted_and = "This HLB is already marked as Completed."
    public var nua = "New Update Available"
    public var upd2 = "Please go to Google Play Store and update this App immediately!"
    public var upd1 = "Update"
    public var lat1 = "Later"
    public var update_downloaded = "Update Downloaded"
    public var unauthorized_access_while_download_upload_data = "This device has been de-enrolled."
    public var title_activity_sup_assigned_eb = "SupAssignedEB"
    public var date_of_birth_format_hint = "DD-MM-YYYY"
    public var npr_toll_free_number = "18001802021"
    public var privacy_policy = "Privacy Policy"
    public var faq = "FAQ"
    public var contact_us = "Contact us"
    public var terms_of_use = "Terms of use"
    public var about_us = "About us"
    public var keyboard_settings = "Keyboard settings"
    public var intro = "Walk-through"
    public var retry = "Retry"
    public var password_changed_message = "Password updated successfully."
    public var view_edit_not_uploaded_message = "Below are the households that were uploaded/updated"
    public var view_edit_uploaded_list_message = "No household data has been uploaded/updated"
    public var invalid_selfenurefno = "Invalid Self Enumeration Number"
    public var seconds_remaining = "seconds remaining: "
    public var validation_name_special_char = "Please enter valid Name."
    public var got_it = "GOT IT"
    public var clear_all_data = "Clear all data"
    public var do_you_want_continue_selected_lang_title = "Do you want to continue with the selected language?"
    public var do_you_want_continue_selected_lang_desc = "The historical data language and the selected language are different. To continue with the selected language, delete the previous data."
   
    public var relationship_to_head = [["name":"Head/Self","id":"01"],
                                       ["name":"Spouse","id":"02"],
                                       ["name":"Son/Daughter","id":"03"],
                                       ["name":"Grand Son/Grand Daughter","id":"04"],
                                       ["name":"Father/Mother","id":"05"],
                                       ["name":"Brother/Sister","id":"06"],
                                       ["name":"Son-in-law/Daughter-in-Law","id":"07"],
                                       ["name":"Grandfather/Grandmother","id":"08"],
                                       ["name":"Father-in-law/Mother-in-law","id":"09"],
                                       ["name":"Other Related person","id":"10"],
                                       ["name":"Domestic Servant","id":"11"],
                                       ["name":"Other Unrelated Person","id":"12"],
                                       ["name":"","id":""]]
    
    public var relationship_to_head_male = [["name":"Head/Self","id":"01"],
                                            ["name":"Spouse","id":"02"],
                                            ["name":"Son","id":"03"],
                                            ["name":"Grand Son","id":"04"],
                                            ["name":"Father","id":"05"],
                                            ["name":"Brother","id":"06"],
                                            ["name":"Son-in-law","id":"07"],
                                            ["name":"Grandfather","id":"08"],
                                            ["name":"Father-in-law","id":"09"],
                                            ["name":"Other Related person","id":"10"],
                                            ["name":"Domestic Servant","id":"11"],
                                            ["name":"Other Unrelated Person","id":"12"],
                                            ["name":"","id":""]]
    
    public var relationship_to_head_female = [["name":"Head/Self","id":"01"],
                                              ["name":"Spouse","id":"02"],
                                              ["name":"Daughter","id":"03"],
                                              ["name":"Grand Daughter","id":"04"],
                                              ["name":"Mother","id":"05"],
                                              ["name":"Sister","id":"06"],
                                              ["name":"Daughter-in-Law","id":"07"],
                                              ["name":"Grandmother","id":"08"],
                                              ["name":"Mother-in-law","id":"09"],
                                              ["name":"Other Related person","id":"10"],
                                              ["name":"Domestic Servant","id":"11"],
                                              ["name":"Other Unrelated Person","id":"12"],
                                              ["name":"","id":""]]
    
    public var relationship_to_head2 = [["name":"Spouse","id":"01"],
                                        ["name":"Son/Daughter","id":"02"],
                                        ["name":"Grand Daughter/Son","id":"03"],
                                        ["name":"Mother/Father","id":"04"],
                                        ["name":"Sister/Brother","id":"05"],
                                        ["name":"Daughter-in Law/Son-in-law","id":"06"],
                                        ["name":"Grandmother/Grandfather","id":"07"],
                                        ["name":"Mother-in-law/Father-in-law","id":"08"],
                                        ["name":"Other Related person","id":"09"],
                                        ["name":"Domestic Servant","id":"10"],
                                        ["name":"Other unrelated person","id":"11"]]
    
    public var relationship_to_head2_male = [["name":"Spouse","id":"01"],
                                             ["name":"Son","id":"02"],
                                             ["name":"Grand Son","id":"03"],
                                             ["name":"Father","id":"04"],
                                             ["name":"Brother","id":"05"],
                                             ["name":"Son-in-law","id":"06"],
                                             ["name":"Grandfather","id":"07"],
                                             ["name":"Father-in-law","id":"08"],
                                             ["name":"Other Related person","id":"09"],
                                             ["name":"Domestic Servant","id":"10"],
                                             ["name":"Other unrelated person","id":"11"]]
    
    public var relationship_to_head2_female = [["name":"Spouse","id":"01"],
                                               ["name":"Daughter","id":"02"],
                                               ["name":"Grand Daughter","id":"03"],
                                               ["name":"Mother","id":"04"],
                                               ["name":"Sister","id":"05"],
                                               ["name":"Daughter-in Law","id":"06"],
                                               ["name":"Grandmother","id":"07"],
                                               ["name":"Mother-in-law","id":"08"],
                                               ["name":"Other Related person","id":"09"],
                                               ["name":"Domestic Servant","id":"10"],
                                               ["name":"Other unrelated person","id":"11"]]
    
    public var marital_statusArr = [["name":"Never Married","id":"1"],["name":"Currently Married","id":"2"],["name":"Widowed","id":"3"],["name":"Seprated","id":"4"],["name":"Divorced","id":"5"]]
    
    public var education_qualification = [["name":"Pre Primary","id":"00"],["name":"Class 1","id":"01"],["name":"Class 2","id":"02"],["name":"Class 3","id":"03"],["name":"Class 4","id":"04"],["name":"Class 5","id":"05"],["name":"Class 6","id":"06"],["name":"Class 7","id":"07"],["name":"Class 8","id":"08"],["name":"Class 9","id":"09"],["name":"Class 10","id":"10"],["name":"Class 11","id":"11"],["name":"Class 12","id":"12"],["name":"ITI","id":"13"],["name":"Polytechnic","id":"14"],["name":"Nursing Diploma","id":"15"],["name":"Teacher Training Diploma","id":"16"],["name":"Certificate/Other Diploma","id":"17"],["name":"Bachelor/Undergraduate","id":"18"],["name":"PG Diploma","id":"19"],["name":"Master/Post graduate","id":"20"],["name":"M.Phil","id":"21"],["name":"Doctorate & above","id":"22"],["name":"Without formal Education","id":"23"],["name":"Illiterate","id":"99"]]
    
    public var occupationArr = [["name":"Cultivator","id":"1"],["name":"Agriculture Labourer","id":"2"],["name":"Daily wages Earner(Other than Agriculture Labourer)","id":"3"],["name":"Single/Family Worker/Self Employed","id":"4"],["name":"Employer","id":"5"],["name":"Government Employee","id":"6"],["name":"Private Employee(Other than Domestic Helper)","id":"7"],["name":"Domestic Helper","id":"8"],["name":"Non Worker","id":"9"]]
    
    
    
    
    
    
}
