//
//  English.swift
//  NPR-2020
//
//  Created by IOS Development Team on 27/01/21.
//  Copyright © 2021 admin. All rights reserved.
//

import Foundation

class KonkaniLang: Encodable {
    
    public var validation_staying_at_present_address_years_not = ""
    public var eb_removed = ""
    public var eb_update = ""
    public var expected_hh_can_not_be_blank = ""
    public var expected_hh_can_not_be_one = ""
    public var age_text = ""
    public var expected_hh_can_not_be_more_than = ""
    public var alert_date = ""
    public var success = ""
    public var error401 = ""
    public var error400 = ""
    public var error204 = ""
    public var fail = ""
    public var norecord = ""
    public var nprstarted = ""
    public var ebstartdateMark = ""
    public var eb_complete_successfully = ""
    public var button_yes = ""
    public var button_no = ""
    public var ebStartDate = ""
    public var searchHeading = ""
    public var app_name = "एनपीआर-2020"
    public var national_population_register = "राष्‍ट्रीय लोकसंख्‍या नोंदणी"
    public var developer_by = "घडवणूक आनी वेवस्‍थापन कृत  "
    public var indian_gov = "ओ.आर.जी. आय, गृह मंत्रालय"
    public var version = "रुप-1.1.1"
    public var please_wait = "मात्‍सो राव"
    public var loading_data = "डेटा भरणी…"
    public var wrong_password = "चुकीचो पासवर्ड"
    public var user_id_password_cant_be_empty = "युजर आयडी पासवर्ड रित्‍यो दवरचो न्‍हय."
    public var connected_to_internet = "बरे ! आंतरजाल जोडले."
    public var not_connected_to_internet = "चुकले !  आंतरजाल संपर्क ना."
    public var total_records = "पूराय अभिलेख- "
    public var total_households = ""
    public var enter_eb_search = ""
    public var select_any_search_type = "खयंचो सोदप्ररुप निवडा"
    public var enter_search_value = "एन्‍टर सर्च व्हँल्यू "
    public var new_hh_added = "नवीन वांगडी आनी कुटूंबाचो समावेश जालो, त्‍याच कुटूंबात आनी एक वांगडी वाडय"
    public var do_you_want_to_continue = "तुका चालू जाय ? "
    public var yes_to_add_more_member = "नवीन वांगडया रवातीर यस दाब, ना जाल्‍यार नो"
    public var choose_any_member_to_mark_as_head = "खयंच्‍या वागंडीची निवड करुन ताका मुखेल नोंद करा "
    public var click_yes_to_mark_as_head = "निवडिल्लो मुखेली जाय, येस दाबा, ना जाल्‍यार नो"
    public var member_updated_successfully = "वागंडयाचे अद्यावतकरण येसस्‍वी"
    public var new_member_added_successfully = "नवो वांगडी जोडलो येसस्‍वी,  त्‍या कुटुंबातलो आनी एक वांगडी वाडय"
    public var sign_by_enumerator_on_behalf_of = "त्‍या वतीन प्रगणकाची सय "
    public var sign_by = "सय-"
    public var please_tick_the_consent = "सहमती टीक करप"
    public var choose_respondent = "उत्‍तरदात्‍याची निवड "
    public var hh_no = "कुटूंब क्रमांक-"
    public var block_no = "गट क्रमांक-"
    public var total_members = "वट्ट वांगडी-"
    public var signature_capture_successful = "सय कब्‍जीत येसस्‍वी."
    public var signature_capturing_cancelled = "सय कब्‍जीत रद्द !"
    public var failed_to_upload_file_check_your_internet_connection = "फायल अद्यावतकरण अपेशी, तुमच्‍या अंतरजालयाची जोडणी तपासा"
    public var file_upload_successfully = "फायल अद्यावतकरण येसस्‍वी."
    public var eb_doesnot_completed_try_again = "ईबी पूराय जावकना परत प्रयत्‍न कराप-"
    public var failed_to_upload_file = "फायल अद्यावतकरण अपेशी-"
    public var connected_network_is_slow_try_again = "नेटवर्क मंद, परत प्रयत्‍न कराप…"
    public var user_doesnot_exist = "युजर आस्तित्‍वात ना."
    public var downloading_data = "डेटा भरणी "
    public var processing_please_wait = "प्रक्रियन, मात्‍से रावाप…"
    public var eb_already_downloaded = "ईबी भरणी जालो "
    public var please_download_eb_to_continue = "ईबी प्रक्रिया चालू दवरात "
    public var failed_to_download_file_please_check_internet = "फायल भरणी अपेशी, तुमच्‍या अंतरजालयाची जोडणी तपासा."
    public var failed_to_download_file = "फायल भरणी अपेशी-"
    public var eb_download_successfully = "ईबी भरणी येसस्‍वी. "
    public var eb_canot_be_download_try_again = "ईबी भरणी करुक शकना, परत करा…"
    public var progress_ = "प्रगती:"
    public var downloaded_at = "भरणी सयत:"
    public var error = "चूक:"
    public var something_went_wrong = "कसली तरी चूक जाल्‍या"
    public var old = "पोरने-"
    public var new_hh = "नवे-"
    public var due_to_hh_not_available = "कुटुंब उपलब्‍ध ना म्हून?"
    public var due_to_family_migrated = "कुटुंब थळातंरीत जाला  "
    public var select_any_option_to_skip = "खयंचो पर्याय स्किप करपाक निवडा"
    public var sr_no_ = "अनुक्रमांक"
    public var resend_otp = "RESEND OTP"
    public var verify_otp_lable = "VERIFY OTP"
    public var clear = "Clear"
    public var save = "Save"
    public var skip = "SKIP"
    public var select_mother_tounge = "Select Mother tongue"
    public var validation_mother_tounge = "Choose Mother tongue"
    public var mother_tounge = "आवय भास"
    public var same_as_present_address = "Permanent Address same as Present Address"
    public var split = "Split"
    public var expected_hh_to_split = "Enter number of household to split the selected household"
    public var hh_spiliting = "Household Spiliting"
    public var hh_split_skip = "None Household will split"
    public var selected_members_will_remain_in_hh = "Select Members which will remain in household no-"
    public var due_to_hh_not_available_ = " due to household not available?"
    public var due_to_family_migrated_ = " due to family migrated?"
    public var due_to_hh_locked = " due to household locked"
    public var due_to_hh_locked_ = " due to household locked?"
    public var login = "लॉगीन"
    public var supervisor_login_title = "पर्यवेक्षक लॉगीन"
    public var userid = "युजर आई डी "
    public var password = "पासवर्ड"
    public var LOGIN = "सय"
    public var sup_logout = "भायर सराप"
    public var select_eb = "खंयचो ईबी निवडा."
    public var not_downloaded = "भरणी जायना"
    public var downloaded = "भरणी जाली "
    public var eb_proceed_comfirmation = "सकल दिल्‍या तपशीलाची तुमकां खात्री आसा ?  "
    public var state = "राज्‍य "
    public var district = "जिल्‍लो"
    public var sub_district = "उप जिल्‍लो "
    public var town_village = "नगर/गांव"
    public var ward = "वार्ड"
    public var block = "गट  "
    public var pincode = "पिन कोड "
    public var DISAGREE = "असहमत"
    public var AGREE = "सहमत"
    public var navigation_drawer_open = "उक्ति मार्ग निर्देशन"
    public var navigation_drawer_close = "बंद मार्ग निर्देशन"
    public var nav_header_title = "Android Studio"
    public var nav_header_subtitle = "android.studio@android.com"
    public var nav_header_desc = "मार्ग निर्देशन मुखेल"
    public var action_settings = "संचक करप"
    public var enter_member_dob_first = "पयली वांगडयाची खरी जल्‍म तारीखेची नोंद करप "
    public var menu_home = "घर"
    public var menu_gallery = "दालन"
    public var menu_slideshow = "स्‍लाइड शो"
    public var menu_tools = "साधन "
    public var menu_share = "वांटप"
    public var menu_send = "धाडप"
    public var location_particular = "थळ तपशील"
    public var hh_summary = "अर्धकुटे कुटुंब "
    public var upload_data = "डेटा अध्‍यावतकरण "
    public var search_edit = "पळोवप/संपादन"
    public var sup_view = "पर्यवेक्षकाची नदर"
    public var sup_ok = "बरे  "
    public var sup_remark = "शेरो"
    public var progress = "प्रगती"
    public var lp_headline = "तुमी दिलेल्‍या कार्यकक्षेत काम करता"
    public var status = "स्थिती"
    public var census_house_no = "घरवळेरीत जनगणना घर क्रमांक"
    public var census_household_no = "घरवेळेरीत जनगणना घर क्रमांक (नवो)"
    public var name = "नांव"
    public var first_name = ""
    public var middle_name = ""
    public var last_name = ""
    public var mobile = "मोबायल "
    public var dob = "जल्‍म तारीख "
    public var head = "मुखेली "
    public var aadhaar = "आधार "
    public var search = "सोद"
    public var proceed = "प्रोसीड "
    public var ad_new_hh = "नवो कुटूंब वागंडी जोडाप"
    public var assign_eb_number = "ईबी सूपूर्द"
    public var hh_number = "कुटुंब क्रमांक"
    public var hh_number2 = "Household Number"
    public var head_of_family_name = "नांव (कुटुंब मुखेली)"
    public var head_of_family_first_name = ""
    public var hh_member_form = "कुटुंब पत्रक "
    public var hh_member_updation_form = "कुटुंब अध्‍यावत पत्रक"
    public var hh_member_addtion = "कुटुंबात नवो वांगडी"
    public var member_added_sucess = "वांगडी जोडाप येसस्‍वी"
    public var in_habitated_eb_completion = ""
    public var signature_captured_cancel = "सय कब्‍जीत रद्द ! "
    public var signature_captured_successfull = "सय कब्‍जीत येसस्‍वी !"
    public var firstly_update_head_present_address_data = "पयली मुखेल्याचो सध्याचो नामो अध्‍यावत करप"
    public var firstly_update_head_p_address_data = "पयली मुखेलीचो स्थायी नामो अध्‍यावत करप"
    public var previous_memebr_details_not_complete = "फाटल्‍या वांगड़याच्‍या पालकांचो डेटा अपूर्ण "
    public var selected_memebr_details_not_complete = "निवडलेल्‍या वागंडाचो तपशील अपूर्ण "
    public var select_father_name = "बापायचे नांव वेंचीव"
    public var select_mother_name = "आंवयचे नांव वेंचीव"
    public var personal_details = "व्‍यक्‍तीगत तपशील "
    public var same_as_head = "स्‍थायी नामो मुखेल्‍या सारखो"
    public var same_as_head_present_address = "सध्याचो नामो मुखेल्‍या सारखो"
    public var parents_same_as_previous = "कुटुंबप्रमुखाच्‍या पालकाक सारखे आदले वांगडी "
    public var parents_are_in_hh = "पालकाक ह्या कुटुंबात राबता"
    public var parents_details = "पालकांचो तपशील"
    public var education_details = "शिक्षण/वेवसाय"
    public var identification_details = "वळख तपशील "
    public var address = "आताचो नामो तपशील"
    public var current_address = "आताचो नामो "
    public var current_address_state = "आता राबता ते राज्‍य"
    public var current_address_district = "आताचो, जिल्‍हो-नामो"
    public var current_address_tehsil = "आताचो-,उपजिल्‍हो-नामो"
    public var permanent_address_details = "स्‍थायी नामो तपशील"
    public var permanent_address = "स्‍थायी नामो देश"
    public var permanent_address2 = "स्‍थायी नामो राज्‍य"
    public var permanent_address3 = "स्‍थायी नामो जिल्‍हो"
    public var permanent_address4 = "स्‍थायी नामो उप-जिल्‍हो"
    public var permanent_address5 = "स्‍थायी नामो नगर/गांव"
    public var permanent_address6 = "स्‍थायी नामो लाईन- 1"
    public var permanent_address7 = "स्‍थायी नामो पिनकोड"
    public var respondent_details = "उत्‍तरदातोचो तपशील "
    public var residential_status = "राबित्‍याची स्थिती"
    public var contact_to_your_supervisor = ""
    public var account_is_not_of_enumerator = ""
    public var account_is_not_of_supervisor = ""
    public var actual = "वास्‍तविक"
    public var intention = "हेतु"
    public var Others = "हेर"
    public var gender = "लिंग"
    public var Male = "दादलो"
    public var Female = "बायल"
    public var trans_gender = "ट्रान्सजेंडर व्यक्ती"
    public var date_of_birth = "जल्‍म तारीख (दिस-म्हयनों-वर्स)"
    public var age = "पिराय"
    public var dob_type = "Date of birth Type"
    public var declared = "जाहीर "
    public var marital_status = "लग्‍न संबंदी स्थिती"
    public var never_married = "केन्‍नाच लग्‍न जावंक ना"
    public var seprated = "वेगळी जाल्‍या"
    public var married = "सदयाक लग्‍न जाला"
    public var widowed = "विधवा"
    public var divorced = "घटस्‍फोट"
    public var nationality = "राष्‍ट्रीयत्‍व"
    public var nationality_declaratation = ""
    public var indian = "भारतीय"
    public var save_member_data = "वांगडाचो डेटा सेव"
    public var f_name = "बापायचे नांव  "
    public var m_name = "आवयचे नांव"
    public var s_name = "बायलेचे नांव "
    public var f_dob = "बापायची जल्‍मतारीख "
    public var m_dob = "आवयची जल्‍मतारीख "
    public var s_dob = "जोड़ीदाराचो जल्‍मतारीख "
    public var f_birth_address = "बापायचो जल्‍म देश "
    public var f_birth_address2 = "बापायचो जल्‍म राज्‍य"
    public var f_birth_address3 = "बापायचो जल्‍म जिल्‍हो"
    public var f_birth_state = "बापायचो जल्‍म राज्‍य"
    public var m_birth_address = "आवयचो जल्‍म देश "
    public var m_birth_address2 = "आवयचो जल्‍म राज्‍य "
    public var m_birth_address3 = "आवयचो जल्‍म जिल्‍हो"
    public var f_birth_district = "बापायचो जल्‍म जिल्‍हो"
    public var m_birth_district = "आवयचो जल्‍म जिल्‍हो"
    public var s_birth_district = "जोड़ीदाराचो जल्‍म जिल्‍हो "
    public var f_birth_village = "बापायचो जल्‍म गांव/नगर"
    public var m_birth_village = "आवयाचो जल्‍म गांव/नगर"
    public var s_birth_village = "जोड़ीदाराचो जल्‍म गांव/नगर"
    public var education = "शिक्षणीक गुणवत्‍ता "
    public var occupation = "वेवसाय"
    public var aadhaar_status = "आधार स्थिती"
    public var aadhaar_available = "आधार उपलब्‍ध"
    public var eid_available = "ईआयडी उपलब्‍ध"
    public var aadhaar_not_available = "उपलब्‍ध ना "
    public var aadhaar_not_enrolled = "वळेरीबद्ध ना"
    public var passport = "पासपोर्ट क्रमांक (जर भारतीय)"
    public var voter_id = "मतदार ओळख क्रमांक"
    public var homeScreen = ""
    public var pan_card = "पॅन कार्ड क्रमांक "
    public var driving_licence = "ड्रायव्‍हीग लायसन क्रमांक"
    public var member_sr_no = "वांगडयाचो वळेरी क्रमांक-"
    public var new_member = "नवो वांगडी  "
    public var wheater_staying_at_present_addres_since_birth = "जल्‍मा पासून ह्याच जाग्‍यार राबता "
    public var years_of_staying = "ह्याच जाग्‍यार राबता  (वर्सा)"
    public var address1 = "घर क्रमांक आनि सुवात "
    public var no_of_hh = "कुटूबाँचो क्रमांक अदमास नोंद करप "
    public var address2 = "नगर/गांव"
    public var respondent_mobile = "उत्‍तरदात्‍याचो मोबाईल क्रमांक"
    public var respondent_name = "उत्‍तरदात्‍याचे नांव"
    public var skip_title = "कुटूब प्रमुख स्‍कीप करपाक कारण निवडा-"
    public var select_head_title = "हया कुटूबातल्‍यान प्रमुख निवडा "
    public var select_sup_eb_title = "खयंचोय ईबी निवडचो"
    public var expected_hh = "अदमासान कुटुंब संख्या"
    public var do_you_want_to_change_the_hh = "तुमंका कुटूब प्रमुखाचो क्रमांक बदलपाक जाय ? "
    public var expected_hh_message = "नेमून दिल्‍या ई.बी चो आदलो डेटा ना "
    public var expected_hh_can_not_be_zero = "वैध्य कुटूंबाचो अदमास नंबर एन्टर करा."
    public var expected_hh_can_not_be_zero_after_eb_upload = ""
    public var enter_remarks = ""
    public var locked_house = "बंद घर"
    public var refused_answer = "उत्‍तर दिवपाक नकार"
    public var not_found = "उपलब्‍ध ना "
    public var family_migrated = "थळातरीत कुटूंब "
    public var house_demolished = "घर मोडले "
    public var other = "हेर "
    public var cancel = "रद्द"
    public var ok = "बरे"
    public var enter_reson_to_skip_household = "कुटूंबप्रमुख स्‍कीप करपाचे कारण नोंद करप"
    public var hh_member_details = "घरातल्‍ल्‍या वागंडयाचो तपशील"
    public var add_member = "वांगडयाची भर घालप "
    public var refresh = "फेर करप "
    public var name_of_person = "नांव "
    public var relationship = "नाते"
    public var sex = "लिंग "
    public var birth_address1 = "जल्मलेलो देश "
    public var birth_address2 = "जल्मलेलो  राज्य "
    public var birth_address3 = "जल्मलेलो  जिल्हों"
    public var birth_tehsil = "जल्‍म उप-जिल्‍हो "
    public var birth_district = "जल्‍म जिल्‍हो"
    public var birth_state = "जल्‍म राज्‍य"
    public var current_house = "आताचो नामो घर आनि सुवात "
    public var current_village = "आताचो गांव नामो"
    public var current_pincode = "आताचो नामो पिनकोड"
    public var current_state = "आताचो नामो राज्‍य"
    public var current_district = "आताचो नामो जिल्‍हो"
    public var current_sub_district = "आताचो नामो उप-जिल्‍हो "
    public var father_birth_address = "बापुय जल्‍मलेलो देश"
    public var father_birth_address2 = "बापुय जल्‍मलेलो राज्‍य"
    public var father_birth_address3 = "बापुय जल्‍मलेलो जिल्‍हो "
    public var mother_birth_address = "आवय जल्‍मलेलो देश "
    public var mother_birth_address2 = "आवय जल्‍मलेलो राज्‍य  "
    public var mother_birth_address3 = "आवय जल्‍मलेलो जिल्‍हो  "
    public var place_of_last_residence = "आदलो राबतालो देश"
    public var place_of_last_residence2 = "आदलो राबतालो राज्‍य "
    public var place_of_last_residence3 = "आदलो राबतालो जिल्‍हो "
    public var member_available = "उपलब्‍ध  "
    public var member_migrated = "स्थलांतरीत "
    public var member_died = "मेला "
    public var serial_number = "क्रमांक सूची "
    public var available = "उपलब्‍ध  "
    public var dead = "मेला "
    public var migrated_out = "भायर गेला"
    public var not_available = "उपलब्‍ध ना "
    public var locked = "बंद "
    public var new_ = "नवो "
    public var signature_required = "उत्‍तरदात्‍याची सय गरजेची "
    public var press_ok_to_take_signature = "उत्‍तरदात्‍याची सय जाय ओके दाबा..."
    public var respondent_signature = "उत्‍तरदात्‍याची सय "
    public var enumerator_signature = "प्रगणकाची सय"
    public var sup_signature = "पर्यवेक्षक सय "
    public var signature_consent = "हांवे सांगलेलो कुटूंबाचो तपशील प्रगणकान अॅपार नोंद केल्‍लो दाखयलो/ वाचून दाखायलो, तो माका स्‍वीकृत/मान्‍य असा, आनी हाव समादानी आसा "
    public var respondant_unable_to_sign_consent = "उत्‍तरदाता सय करुक सकना म्‍हून प्रगणकांन उत्‍तरदात्याच्या उपस्थितीत वाचले आनी सय केले."
    public var respondent = "उत्‍तरदातो "
    public var emulator_status = "प्रगणकाची स्थिती "
    public var next = "NEXT"
    public var total_assigned_eb = "नेमून दिल्‍लो ई बी ची वट्ट "
    public var uploaded_eb = "अद्यावतकरण ईबीची वट्ट "
    public var pending_eb = "प्रलंबीत ईबीची वट्ट "
    public var current_eb_status = "चालंत ईबीची स्थिती"
    public var eb_number = ""
    public var household_status = ""
    public var total_original_household = ""
    public var total_available_households = ""
    public var total_migrated_hh = "स्‍थानातरण कुटुंबाची वट्ट "
    public var total_locked_hh = "बंद कुंटुबाची वट्ट"
    public var total_not_available_hh = "उपलब्‍ध नसलेल्‍या कुंटूंबाची वट्ट "
    public var total_new_hh = "वट्ट नवी कुटुंबा"
    public var total_households_original_new = ""
    public var total_updated_households = ""
    public var total_pending_households = ""
    public var member_status = "वागंडयाची स्थिती"
    public var total_original_members = ""
    public var available_members = ""
    public var dead_member = "मेलेलो वागंडी"
    public var migrated_member = "स्‍थानातंरीत वागंडी"
    public var total_new_members = ""
    public var total_updated_members = ""
    public var total_members_original_new = ""
    public var members_yet_to_be_udated = ""
    public var member_with_passport = "पासपोर्ट आसलेले वागंडी "
    public var member_with_aadhaar = "आधारकार्ड आसलेले वागंडी "
    public var members_with_mobile_number = ""
    public var member_with_voterID = "मतदारकार्ड आसलेले वागंडी "
    public var member_with_dl = "ड्रायविंग लायसन आसलेले वागंडी"
    public var total_house_hold = "वट्ट कुटुंबा "
    public var total_old_hh = "पैलीची वट्ट कुटुंबा "
    public var total_npr_member = "एनपीआर वागंडाची वट्ट "
    public var total_updated_npr_member = "अद्यावतरण केल्‍ल्‍या एनपीआर वागंडाची वट्ट "
    public var member_with_pancard = "पॅनकार्ड आसलेले वागंडी "
    public var na_member = "उपलब्‍ध नसलेले वागंडी "
    public var loced_member = "बंद आसलेले वागंडी "
    public var total_old_member = "पैलीचे वांगड्याची वट्ट "
    public var total_old_member_found = "पैलीचे वांगडी मेळे"
    public var total_migrated_member = "स्‍थानातंरीत वांगड्याची वट्ट "
    public var total_new_member = "नव्‍या वांगड्याची वट्ट "
    public var total_new_member_with_passport = "पासपोर्ट आसलेल्‍या नव्‍या वांगड्याची वट्ट "
    public var total_new_member_with_aadhaar = "आधारकार्ड आसलेल्‍या नव्‍या वांगड्याची वट्ट "
    public var total_new_member_with_voterID = "मतदारकार्ड आसलेल्‍या नव्‍या वांगड्याची वट्ट "
    public var total_new_member_with_dl = "ड्रायविंग लायसन आसलेले नव्‍या वांगड्याची वट्ट "
    public var total_new_member_with_pancard = "पॅनकार्ड आसलेले नव्‍या वांगड्याची वट्ट"
    public var pending_members = "प्रलंबित वांगडी "
    public var total_members_found = "सगल्‍या वांगड्याची वट्ट "
    public var choose_country = "खयंचोय देश निवडा "
    public var choose_state = "खंयचेय राज्‍य निवडा "
    public var choose_Nationality = ""
    public var choose_district = "खयंचोय जिल्‍हो निवडा "
    public var choose_tehsil = "खयचोय उपजिल्‍लो निवडा "
    public var choose_respondant = "उत्‍तरदात्याचे नांव निवडा "
    public var yes = "हय"
    public var no = "ना"
    public var reload_master_directory = "मुखेली निदेशिकाची पुर्नभरणी "
    public var sup_remark_length = "शेरो अपेशी,  शे-यात कमीत कमी 3 संज्ञा जाय"
    public var submit = "सबमिट"
    public var button_save = "सेव"
    public var button_update = "अद्यावतकरण "
    public var button_add_member = "वागंड जोडणी "
    public var hh_skipped = "कुटुंब क्रमांक येसस्‍वी स्‍कीप- "
    public var member_migrated_successfully = "स्‍थानांतरण वागंडीची येसस्‍वी नोंद "
    public var member_dead_successfully = "मेल्‍लया सदस्‍याची येसस्‍वी नोंद"
    public var are_you_sure = "तुमका खात्री आसा?  "
    public var to_exit_from_app = "पर्यवेक्षक लॉग ऑउट करा?"
    public var alert = "शिटूकावणी"
    public var eb_completion_alert1 = "पूर्व डेटा पुराय जाल्‍याउपरान, तुमका ईबी पुराय जालो अशे नोंद करपाक जाय ? "
    public var eb_completion_alert2_title = "आताचो ईबी पुराय जालो अशी नोंद करपाची तुमची खात्री आसा ? "
    public var eb_completion_alert2 = "यस केल्‍यार तुमका कसलोच बदल करुक मेळचेना ह्या ईबीत, ना जाल्‍यार नो करा"
    public var enumerator_sign = "प्रगणकाची सय सकल..."
    public var sup_sign = "पर्यवेक्षकाची सय सकल..."
    public var to_skip_hh = "कुटुंबाचो क्रमांक स्‍कीप करा "
    public var to_mark_member = "सदस्‍य क्रमांक नोंद करप-"
    public var as_migrated = "स्थलांतरण केल्ले"
    public var as_dead = "मेल्‍लो"
    public var are_you_sure_to_exit_from_hh_form = ""
    public var due_to_locked = "बंद आसा म्हून खातीर?"
    public var are_you_sure_to_exit = "तुमी भायर सरता? "
    public var you_will_loss_data = "तुमी येस केल्‍यार, डेटा ना जातलो (अध्यावत केल्‍लो)"
    public var user_does_not_exist = "वापरपी दिसाना "
    public var please_check_your_internet_connection = "उपकार करुन तुमची आंतरजाल जोडणी तपासा "
    public var wrong_login_type = "तुमी चुकीचो लॉगइन टायप करता "
    public var no_imei_or_logintype_passed = "आयएमईआय वा लॉगईन टायप ना "
    public var imei_exist = "आदल्‍या सायइन  च्‍या खात्‍यातून लॉगआऊट करा ?"
    public var cancel_hit = "विनंती रद्द "
    public var verify_otp = "ओटीपी पारखवणी "
    public var otp_send_on = "ओटीपी धाडल्‍या- "
    public var please_enter_correct_otp = "योग्‍य ओटीपीची नोंद करप "
    public var signin_sucess = "सय येसस्‍वी "
    public var signin_sucess_in_another_device = "ह्या साधनता नोंद येसस्‍वी, आनी आदले साधनाची नोंद रद्द."
    public var eb_not_alloted = "आजून या युजराक ईबी वाटप जावकना "
    public var upload_eb = "ईबी अद्यावतरण करात "
    public var uploaded = "अद्यावतरण जाले "
    public var resend_otp_success = "परत धाडलेलो ओटीपी येसस्‍वी "
    public var forgot_password = "पासवर्ड विसरलो"
    public var supervisor_login = "पर्यवेक्षाक लॉगइन "
    public var registered_userId = "नोंदणीकृत युजर आई डी "
    public var new_password = "नवो पासवर्ड "
    public var retype_password = "परत पासवर्ड टाईप कर "
    public var chnage_password_via_otp = "ओटीपी तून पासवर्ड बदला "
    public var CHANGE_PASSWORD = "पासवर्ड बदल कर"
    public var password_field_can_not_be_blank = "पासवर्ड जागो रितें दवरप ना "
    public var both_password_should_be_same = "दोनी पासवर्ड सारखे जाय "
    public var password_chnaged = "पासवर्ड बदल्‍लो "
    public var please_login_again = "नवो पासवर्ड घालून परत लॉगईन करा "
    public var no_member_to_make_head = "हेर वागंडी नासताना कुंटूंबप्रमुख बदलू शकना, भायर सरपाक रद्द करा"
    public var no_eb_to_choose_for_this_sup = " या प्रगणकाच्या ईबीचे पर्यवेक्षण करपाक तुमका  वाटप करुक ना "
    public var do_you_want_to_upload_locked_hh_also1 = "ते आसा "
    public var do_you_want_to_upload_locked_hh_also2 = "बंद घर/कुंटूब अद्यावतरण करुक जाय, येस करा, ना जाल्‍यार नो (बंद घर/कुंटूंब सोडून पुराय अभिलेख अद्यावतरण जातलो)"
    public var eb_mark_as_completed = "ईबी भरणी येसस्‍वी "
    public var device_is_de_registered_so_not_allowed_yo_upload = "रद्द जालेल्‍या साधनातून तुमका अद्यावतरण करुक मेळना "
    public var validation_census_house_no = "घरवेळेरीत जनगणना घर क्रमांक तपासा, ते रिते दवरपाक ना "
    public var validation_census_house_no_zero = ""
    public var validation_new_census_household_no_zero = ""
    public var you_have_complted_10_hh_please_upload = ""
    public var you_have_complted_50_member_please_upload = ""
    public var validation_new_census_household_no = "नवी घरवेळेरीतून कुंटूंबक्रमांक तपासा "
    public var validation_name = "कमीट कमी 3 संज्ञेत नांव जाय"
    public var validation_first_name = ""
    public var validation_first_name_startwith = ""
    public var validation_middle_name = ""
    public var validation_middle_name_startwith = ""
    public var validation_last_name = ""
    public var validation_last_name_startwith = ""
    public var validation_hh_no = "कुटूंबप्रमुखाचो क्रमांक ग्राह्य जाय "
    public var validation_hh_no_already_exist = "कुटूंबप्रमुखाचो क्रमांक पयलीच आसा"
    public var validation_newchh_no_already_exist = "नव्‍या घरवळेरीत जनगणना घर क्रमांक पयलीच दिसता"
    public var validation_hh_family_membr_no = "कुंटूंब सदस्‍याचो क्रमांक ग्राह्य जाय "
    public var validation_relationship = "कुटूंब प्रमुखाची नाते निवडा"
    public var validation_nationality = "राष्‍ट्रीयत्‍व 3 संज्ञेत बरयात "
    public var feild_should_not = ""
    public var validation_gender = "लिंग निवडा "
    public var validation_marital_status = "लग्‍नास्थिती निवडा "
    public var validation_member_dob = "वांग‍डीची जल्‍मतारीख रिती दवरप ना"
    public var validation_member_dob_not_valid = "उपकारकरुन ग्राह्य जल्‍मतारीखेची नोंद करा "
    public var validation_dob_date_today_date = "जल्‍मतारीख ह्या दिसाची आसू नये "
    public var validation_dob_date_future_date = "जल्‍मतारीख भविष्‍यातली आसू नये "
    public var validation_member_birthcountry = "जल्‍मदेश निवडा "
    public var validation_member_birthstate = "जल्‍म राज्‍य निवडा"
    public var validation_member_birthdistrict = "जल्‍म जिल्‍लो निवडा "
    public var validation_member_Nationality = ""
    public var validation_member_birthtehsil = "जल्‍म उप-जिल्‍लो निवडा "
    public var validation_education = "शिक्षणीक गुणवत्‍ता निवडा"
    public var validation_occupation = "वेवसाय निवडा "
    public var validation_present_state = "आताच्‍या नाम्‍यात राज्‍य निवडा "
    public var validation_present_district = "आताचो जिल्‍ला निवडा"
    public var validation_present_sub_district = "आताचो उप-जिल्‍लो निवडा "
    public var validation_present_address1 = "आताच्‍या नाम्‍यातलो घर क्रमांक आनी स्‍थान तपासा"
    public var validation_present_address2 = "आताच्‍या नाम्‍यातलो नगर/गाव तपासा"
    public var validation_present_pincode = "आताचो पिन कोड तपासा"
    public var validation_permaneent_country = "स्‍थायी नामो देश निवडा"
    public var validation_permaneent_state = "स्‍थायी नामो राज्‍य निवडा"
    public var validation_permaneent_district = "स्‍थायी नामो जिल्‍लो निवडा"
    public var validation_permaneent_tehsil = "स्‍थायी नामो उप-जिल्‍लो"
    public var validation_permaneent_address1 = "घर क्रमांक/स्‍थान तपासा "
    public var validation_permaneent_address2 = "नगर/गांव तपासा "
    public var validation_permaneent_pincode = "स्‍थायी पिन कोड तपासा"
    public var validation_staying_at_present_address_yes_no = "निवडा जल्मापासून सध्याच्या नाम्यार रावता"
    public var validation_staying_at_present_address_years = "रावतो नामो रितो सोडप ना"
    public var validation_staying_at_present_address_years_can_not_be_more_than_age = ""
    public var validation_staying_at_present_address_years_invalid = "आताचो नामो वागंडयाच्‍या पिराय परस चड आसू नये "
    public var validation_last_residence_country = "आदलो राबतालो देश"
    public var validation_last_residence_state = "आदलो राबतालो राज्‍य "
    public var validation_last_residence_district = "आदलो राबतालो जिल्‍लो "
    public var validation_father_name = "बापायचे नांव तीन संज्ञेचे जाय "
    public var validation_father_dob = "बापायची जल्‍मतारीख रिती नाका "
    public var validation_father_dob_today_date = "बापायची जल्‍मतारीख वर्तमान आसू नये "
    public var validation_father_dob_future_date = "बापायची जल्‍मतारीख भविष्‍यातली आसू नये "
    public var validation_mother_dob_not_valid = "आवयची ग्राह्य जल्‍मतारीख नोंद करप"
    public var validation_father_dob_not_valid = "बापायची ग्राह्य जल्‍मतारीख नोंद करप "
    public var validation_father_dob_with_member_same = "बापायची आनी हेर वागंडयांची जल्‍मतारीख एकूच आसू नये"
    public var validation_father_birth_country = "बापायचो जल्‍म देश निवडा"
    public var validation_father_birth_state = "बापायचो जल्‍म राज्‍य निवडा"
    public var validation_father_birth_district = "बापायचो जल्‍म जिल्‍लो निवडा"
    public var validation_mother_name = "आवयचे नांव तीन संज्ञेचे जाय"
    public var validation_mother_dob = "आवयची जल्‍म तारीख रिती नाका"
    public var validation_mother_birth_country = "आवयचो जल्‍म देश निवडा "
    public var validation_mother_birth_state = "आवयचो जल्‍म राज्‍य निवडा"
    public var validation_mother_birth_district = "आवयचो जल्‍म जिल्‍लो निवडा"
    public var validation_spouse_name = "जोड़ीदाराचे नांव 3 संज्ञेचे जाय"
    public var validation_aadhaar = "ग्राह्य आधारकार्ड क्रमांक नोंद करा "
    public var validation_mobile = "मोबायल क्रमांक तपासा "
    public var validation_passport = "पासपोर्ट क्रमांक तपासा "
    public var validation_voterid = "मतदार कार्ड तपासा "
    public var validation_pan_card = "ग्राह्य पॅनकार्ड क्रमांक नोंद करा "
    public var validation_dl = "ड्रायविंग लायसन क्रमांक तपासा "
    public var validation_respondent_name = "उत्‍तरदात्याचे नांव 3 संज्ञेचे जाय"
    public var validation_respondent_mobile = "उत्‍तरदातेचो मोबायल क्रमांक तपासा"
    public var validation_spouse_name_blank = ""
    public var data_clear_open_app_again = "अॅप डेटा पुराय जाला, परत अॅप उकते करा"
    public var shift = "Shift"
    public var to_shift = "To shift"
    public var select_hh_for_member_shifting = "Select HouseHold to shift selected Member"
    public var choose_any_hh_to_shift_member = "Choose any hosuehold to shift selected member"
    public var db_reload = "After press OK your current data will be delete and your last synch data will be added."
    public var selected_members_are = "Selected Members are = "
    public var remaning_members = "Remaining Members = "
    public var select_any_member_to_split = "Please select any member first to split"
    public var spliting_completed = "Spiliting completed"
    public var first_member_sr_no = ""
    public var first_hh_no = ""
    public var failed_to_download_file_no_data_found = ""
    public var recovery = "Recovery"
    public var hh_type = ""
    public var normal = ""
    public var institutional = ""
    public var houseless = ""
    public var check_hh_type = ""
    public var name_of_institue = ""
    public var validation_name_of_institution = ""
    public var delete = ""
    public var to_delete = ""
    public var to_delete_hh = ""
    public var head_delete_message = ""
    public var member_deleted_sucess_message1 = ""
    public var member_deleted_sucess_message2 = ""
    public var self_enu_ref_no = ""
    public var enter_mother_tounge = ""
    public var validation_mother_tounge_1 = ""
    public var other_mother_tongue = ""
    public var error_wile_connecting_to_server = ""
    public var connecting_to_server = ""
    public var downloading_required_data = ""
    public var activated_devic_title = ""
    public var same_device_already_activated = ""
    public var switch_eb = ""
    public var no_eb = ""
    public var language_error = "\"आपण मराठी आपली प्राधान्य म्हणून निवडले आहे. कृपया आपल्या कीबोर्ड सेटिंग्ज हिंदीमध्ये बदला.\""
    public var no_data = ""
    public var search_dob = ""
    public var search_aadhaar = ""
    public var search_name = ""
    public var search_head = ""
    public var search_mobile = ""
    public var enter_search_name = ""
    public var enter_search_dob = ""
    public var enter_search_aadhaar = ""
    public var enter_search_head = ""
    public var enter_search_mobile = ""
    public var select_any_option_to_search = ""
    public var search_head_name_from_hlo = ""
    public var aadhar_detail_alert = ""
    public var relationship_with_head = ""
    public var permanent_address_same_as_member = ""
    public var country = ""
    public var choose_member = ""
    public var de_enroll_message1 = ""
    public var de_enroll_message2 = ""
    public var census_housing_number = ""
    public var census_house_hold_number = ""
    public var search_for_mother_tongue = ""
    public var loading = ""
    public var field_should_not_be_blank = ""
    public var validation_age = ""
    public var user_not_enrolled_for_mobile_application = ""
    public var email_id_not_available = ""
    public var server_error = ""
    public var unauthorized_access = ""
    public var invalid_otp = ""
    public var required_resources_downloaded_successfully = ""
    public var cancel_lower = ""
    public var OK = ""
    public var restart = ""
    public var server_connection_issue = ""
    public var connection_failed_due_to = ""
    public var failed = ""
    public var mother_tongue_already_present = ""
    public var no_data_to_upload = ""
    public var initializing_please_wait = ""
    public var retry_upload = ""
    public var upload_from_previous_device = ""
    public var validation_both_password_length = ""
    public var already_marked_as_complted_and_uninhabited = ""
    public var already_marked_as_complted_and = ""
    public var nua = ""
    public var upd2 = ""
    public var upd1 = ""
    public var lat1 = ""
    public var update_downloaded = ""
    public var unauthorized_access_while_download_upload_data = ""
    public var title_activity_sup_assigned_eb = ""
    public var date_of_birth_format_hint = ""
    public var npr_toll_free_number = ""
    public var privacy_policy = "Privacy Policy"
    public var faq = "FAQ"
    public var contact_us = "Contact us"
    public var terms_of_use = ""
    public var about_us = "About us"
    public var keyboard_settings = ""
    public var intro = ""
    public var retry = ""
    public var password_changed_message = ""
    public var view_edit_not_uploaded_message = ""
    public var view_edit_uploaded_list_message = ""
    public var invalid_selfenurefno = ""
    public var seconds_remaining = ""
    public var validation_name_special_char = ""
    public var got_it = "GOT IT"
    public var clear_all_data = ""
    public var do_you_want_continue_selected_lang_title = ""
    public var do_you_want_continue_selected_lang_desc = ""
    public var number_of_member_in_family = "कुटुंबाचे वट्ट वागडी (ईजी.99)"
    public var validation_father_dob_with_member_less = "बापयची जल्‍मतारीख वागंडयाची जल्‍मतारीखेपरस कमी आसू नये"
    
    public var relationship_to_head = [["name":"Head/Self","id":"01"],
                                       ["name":"Spouse","id":"02"],
                                       ["name":"Son/Daughter","id":"03"],
                                       ["name":"Grand Son/Grand Daughter","id":"04"],
                                       ["name":"Father/Mother","id":"05"],
                                       ["name":"Brother/Sister","id":"06"],
                                       ["name":"Son-in-law/Daughter-in-Law","id":"07"],
                                       ["name":"Grandfather/Grandmother","id":"08"],
                                       ["name":"Father-in-law/Mother-in-law","id":"09"],
                                       ["name":"Other Related person","id":"10"],
                                       ["name":"Domestic Servant","id":"11"],
                                       ["name":"Other Unrelated Person","id":"12"],
                                       ["name":"","id":""]]
    
    public var relationship_to_head_male = [["name":"Head/Self","id":"01"],
                                            ["name":"Spouse","id":"02"],
                                            ["name":"Son","id":"03"],
                                            ["name":"Grand Son","id":"04"],
                                            ["name":"Father","id":"05"],
                                            ["name":"Brother","id":"06"],
                                            ["name":"Son-in-law","id":"07"],
                                            ["name":"Grandfather","id":"08"],
                                            ["name":"Father-in-law","id":"09"],
                                            ["name":"Other Related person","id":"10"],
                                            ["name":"Domestic Servant","id":"11"],
                                            ["name":"Other Unrelated Person","id":"12"],
                                            ["name":"","id":""]]
    
    public var relationship_to_head_female = [["name":"Head/Self","id":"01"],
                                              ["name":"Spouse","id":"02"],
                                              ["name":"Daughter","id":"03"],
                                              ["name":"Grand Daughter","id":"04"],
                                              ["name":"Mother","id":"05"],
                                              ["name":"Sister","id":"06"],
                                              ["name":"Daughter-in-Law","id":"07"],
                                              ["name":"Grandmother","id":"08"],
                                              ["name":"Mother-in-law","id":"09"],
                                              ["name":"Other Related person","id":"10"],
                                              ["name":"Domestic Servant","id":"11"],
                                              ["name":"Other Unrelated Person","id":"12"],
                                              ["name":"","id":""]]
    
    public var relationship_to_head2 = [["name":"Spouse","id":"01"],
                                        ["name":"Son/Daughter","id":"02"],
                                        ["name":"Grand Daughter/Son","id":"03"],
                                        ["name":"Mother/Father","id":"04"],
                                        ["name":"Sister/Brother","id":"05"],
                                        ["name":"Daughter-in Law/Son-in-law","id":"06"],
                                        ["name":"Grandmother/Grandfather","id":"07"],
                                        ["name":"Mother-in-law/Father-in-law","id":"08"],
                                        ["name":"Other Related person","id":"09"],
                                        ["name":"Domestic Servant","id":"10"],
                                        ["name":"Other unrelated person","id":"11"]]
    
    public var relationship_to_head2_male = [["name":"Spouse","id":"01"],
                                             ["name":"Son","id":"02"],
                                             ["name":"Grand Son","id":"03"],
                                             ["name":"Father","id":"04"],
                                             ["name":"Brother","id":"05"],
                                             ["name":"Son-in-law","id":"06"],
                                             ["name":"Grandfather","id":"07"],
                                             ["name":"Father-in-law","id":"08"],
                                             ["name":"Other Related person","id":"09"],
                                             ["name":"Domestic Servant","id":"10"],
                                             ["name":"Other unrelated person","id":"11"]]
    
    public var relationship_to_head2_female = [["name":"Spouse","id":"01"],
                                               ["name":"Daughter","id":"02"],
                                               ["name":"Grand Daughter","id":"03"],
                                               ["name":"Mother","id":"04"],
                                               ["name":"Sister","id":"05"],
                                               ["name":"Daughter-in Law","id":"06"],
                                               ["name":"Grandmother","id":"07"],
                                               ["name":"Mother-in-law","id":"08"],
                                               ["name":"Other Related person","id":"09"],
                                               ["name":"Domestic Servant","id":"10"],
                                               ["name":"Other unrelated person","id":"11"]]
    
    public var marital_statusArr = [["name":"Never Married","id":"1"],
                                    ["name":"Currently Married","id":"2"],
                                    ["name":"Widowed","id":"3"],
                                    ["name":"Seprated","id":"4"],
                                    ["name":"Divorced","id":"5"]]
    
    public var education_qualification = [["name":"Pre-Primary","id":"00"],
                                          ["name":"Class 1","id":"01"],
                                          ["name":"Class 2","id":"02"],
                                          ["name":"Class 3","id":"03"],
                                          ["name":"Class 4","id":"04"],
                                          ["name":"Class 5","id":"05"],
                                          ["name":"Class 6","id":"06"],
                                          ["name":"Class 7","id":"07"],
                                          ["name":"Class 8","id":"08"],
                                          ["name":"Class 9","id":"09"],
                                          ["name":"Class 10","id":"10"],
                                          ["name":"Class 11","id":"11"],
                                          ["name":"Class 12","id":"12"],
                                          ["name":"ITI","id":"13"],
                                          ["name":"Polytechnic","id":"14"],
                                          ["name":"Nursing Diploma","id":"15"],
                                          ["name":"Teacher Training Diploma","id":"16"],
                                          ["name":"Certificate/Other Diploma","id":"17"],
                                          ["name":"Bachelor/Undergraduate","id":"18"],
                                          ["name":"PG Diploma","id":"19"],
                                          ["name":"Master/Post graduate","id":"20"],
                                          ["name":"M.Phil","id":"21"],
                                          ["name":"Doctorate & above","id":"22"],
                                          ["name":"Without formal Education","id":"23"],
                                          ["name":"Illiterate","id":"99"]]
    
    public var occupationArr = [["name":"Cultivator","id":"1"],
                                ["name":"Agriculture Labourer","id":"2"],
                                ["name":"Daily wages Earner(Other than Agriculture Labourer)","id":"3"],
                                ["name":"Single/Family Worker/Self Employed","id":"4"],
                                ["name":"Employer","id":"5"],["name":"Government Employee","id":"6"],
                                ["name":"Private Employee(Other than Domestic Helper)","id":"7"],
                                ["name":"Domestic Helper","id":"8"],
                                ["name":"Non-Worker","id":"9"]]
    
}
