//
//  English.swift
//  NPR-2020
//
//  Created by IOS Development Team on 27/01/21.
//  Copyright © 2021 admin. All rights reserved.
//

import Foundation

class LanguageModal: Decodable {
    
    public static var langObj = LanguageModal()
    public static var currentLanguage = "English"
//    public var validation_staying_at_present_address_years_not = ""
    public var eb_removed = ""
    public var eb_update = ""
    public var expected_hh_can_not_be_blank = ""
    public var expected_hh_can_not_be_one = ""
    public var age_text = ""
    public var expected_hh_can_not_be_more_than = ""
    public var alert_date = ""
    public var success = ""
    public var error401 = ""
    public var error400 = ""
    public var error204 = ""
    public var fail = ""
    public var incorrect_SE = ""
    public var norecord = ""
    public var nprstarted = ""
    public var ebstartdateMark = ""
    public var eb_complete_successfully = ""
    public var button_yes = ""
    public var button_no = ""
    public var ebStartDate = ""
    public var searchHeading = ""
   // public var app_name = ""
    public var national_population_register = ""
    public var developer_by = ""
    public var indian_gov = ""
    public var version = ""
    public var please_wait = ""
    public var loading_data = ""
    public var wrong_password = ""
    public var user_id_password_cant_be_empty = ""
    public var connected_to_internet = ""
    public var not_connected_to_internet = ""
    public var total_records = ""
    public var total_households = ""
    public var enter_eb_search = ""
    public var select_any_search_type = ""
    public var enter_search_value = ""
    public var new_hh_added = ""
    public var do_you_want_to_continue = ""
    public var yes_to_add_more_member = ""
    public var choose_any_member_to_mark_as_head = ""
    public var click_yes_to_mark_as_head = ""
    public var member_updated_successfully = ""
    public var new_member_added_successfully = ""
    public var sign_by_enumerator_on_behalf_of = ""
    public var sign_by = ""
    public var please_tick_the_consent = ""
    public var choose_respondent = ""
    public var hh_no = ""
    public var block_no = ""
    public var total_members = ""
    public var signature_capture_successful = ""
    public var signature_capturing_cancelled = ""
    public var failed_to_upload_file_check_your_internet_connection = ""
    public var file_upload_successfully = ""
    public var eb_doesnot_completed_try_again = ""
    public var failed_to_upload_file = ""
    public var connected_network_is_slow_try_again = ""
    public var user_doesnot_exist = ""
    public var downloading_data = ""
    public var processing_please_wait = ""
    public var eb_already_downloaded = ""
    public var please_download_eb_to_continue = ""
    public var failed_to_download_file_please_check_internet = ""
    public var failed_to_download_file = ""
    public var eb_download_successfully = ""
    public var eb_canot_be_download_try_again = ""
    public var progress_ = ""
    public var downloaded_at = ""
    public var error = ""
    public var something_went_wrong = ""
    public var old = ""
    public var new_hh = ""
    public var due_to_hh_not_available = ""
    public var due_to_family_migrated = ""
    public var select_any_option_to_skip = ""
    public var sr_no_ = ""
    public var resend_otp = ""
    public var verify_otp_lable = ""
    public var clear = ""
    public var save = ""
    public var skip = ""
    public var select_mother_tounge = ""
    public var validation_mother_tounge = ""
    public var mother_tounge = ""
    public var same_as_present_address = ""
    public var split = ""
    public var expected_hh_to_split = ""
    public var hh_spiliting = ""
    public var hh_split_skip = ""
    public var selected_members_will_remain_in_hh = ""
    public var due_to_hh_not_available_ = ""
    public var due_to_family_migrated_ = ""
    public var due_to_hh_locked = ""
    public var due_to_hh_locked_ = ""
    public var login = ""
    public var supervisor_login_title = ""
    public var userid = ""
    public var password = ""
    public var LOGIN = ""
    public var sup_logout = ""
    public var select_eb = ""
    public var not_downloaded = ""
    public var downloaded = ""
    public var eb_proceed_comfirmation = ""
    public var state = ""
    public var district = ""
    public var sub_district = ""
    public var town_village = ""
    public var ward = ""
    public var block = ""
    public var pincode = ""
    public var DISAGREE = ""
    public var AGREE = ""
   // public var navigation_drawer_open = ""
   // public var navigation_drawer_close = ""
  //  public var nav_header_title = ""
    //public var nav_header_subtitle = ""
   // public var nav_header_desc = ""
    public var action_settings = ""
    public var enter_member_dob_first = ""
   // public var menu_home = ""
   // public var menu_gallery = ""
   // public var menu_slideshow = ""
   // public var menu_tools = ""
    public var menu_share = ""
   // public var menu_send = ""
    public var location_particular = ""
    public var hh_summary = ""
    public var upload_data = ""
    public var search_edit = ""
    public var sup_view = ""
    public var sup_ok = ""
    public var sup_remark = ""
    public var progress = ""
    public var lp_headline = ""
    public var status = ""
    public var census_house_no = ""
    public var census_household_no = ""
    public var name = ""
    public var first_name = ""
    public var first_name_can_not_be_empty = ""
    public var first_middle_last_name_should_be_2_char_length = ""
    public var first_middle_name_should_be_2_char_length = ""
    public var first_last_name_should_be_2_char_length = ""
    public var middle_name = ""
    public var last_name = ""
    public var mobile = ""
    public var dob = ""
    public var head = ""
    public var aadhaar = ""
    public var search = ""
    public var proceed = ""
    public var ad_new_hh = ""
    public var assign_eb_number = ""
    public var hh_number = ""
    public var hh_number2 = ""
    public var head_of_family_name = ""
    public var head_of_family_first_name = ""
    public var number_of_member_in_family  = ""
    public var hh_member_form = ""
    public var hh_member_updation_form = ""
    public var hh_member_addtion = ""
    public var member_added_sucess = ""
    public var in_habitated_eb_completion = ""
    public var signature_captured_cancel = ""
    public var signature_captured_successfull = ""
    public var firstly_update_head_present_address_data = ""
    public var firstly_update_head_p_address_data = ""
    public var previous_memebr_details_not_complete = ""
    public var selected_memebr_details_not_complete = ""
    public var select_father_name = ""
    public var select_mother_name = ""
    public var personal_details = ""
    public var same_as_head = ""
    public var same_as_head_present_address = ""
    public var parents_same_as_previous = ""
    public var parents_are_in_hh = ""
    public var parents_details = ""
    public var education_details = ""
    public var validation_age_parents = ""
    public var identification_details = ""
    public var address = ""
    public var current_address = ""
    public var current_address_state = ""
    public var current_address_district = ""
    public var current_address_tehsil = ""
    public var permanent_address_details = ""
    public var permanent_address = ""
    public var permanent_address2 = ""
    public var permanent_address3 = ""
    public var permanent_address4 = ""
    public var permanent_address5 = ""
    public var permanent_address6 = ""
    public var permanent_address7 = ""
    public var respondent_details = ""
    public var residential_status = ""
    public var contact_to_your_supervisor = ""
    public var account_is_not_of_enumerator = ""
    public var account_is_not_of_supervisor = ""
    public var actual = ""
    public var intention = ""
    public var Others = ""
    public var gender = ""
    public var Male = ""
    public var Female = ""
    public var trans_gender = ""
    public var date_of_birth = ""
    public var age = ""
    public var dob_type = ""
    public var declared = ""
    public var marital_status = ""
    public var never_married = ""
    public var seprated = ""
    public var married = ""
    public var widowed = ""
    public var divorced = ""
    public var nationality = ""
    public var nationality_declaratation = ""
    public var indian = ""
    public var save_member_data = ""
    public var f_name = ""
    public var m_name = ""
    public var s_name = ""
    public var f_dob = ""
    public var m_dob = ""
    public var s_dob = ""
    public var f_birth_address = ""
    public var f_birth_address2 = ""
    public var f_birth_address3 = ""
    public var f_birth_state = ""
    public var m_birth_address = ""
    public var m_birth_address2 = ""
    public var m_birth_address3 = ""
    public var f_birth_district = ""
    public var m_birth_district = ""
    public var s_birth_district = ""
    public var f_birth_village = ""
    public var m_birth_village = ""
    public var s_birth_village = ""
    public var education = ""
    public var occupation = ""
    public var aadhaar_status = ""
    public var aadhaar_available = ""
    public var eid_available = ""
    public var aadhaar_not_available = ""
    public var aadhaar_not_enrolled = ""
    public var passport = ""
    public var voter_id = ""
    public var homeScreen = ""
    public var pan_card = ""
    public var driving_licence = ""
    public var member_sr_no = ""
    public var new_member = ""
    public var wheater_staying_at_present_addres_since_birth = ""
    public var years_of_staying = ""
    public var address1 = ""
    public var no_of_hh = ""
    public var address2 = ""
    public var respondent_mobile = ""
    public var respondent_name = ""
    public var skip_title = ""
    public var select_head_title = ""
    public var select_sup_eb_title = ""
    public var expected_hh = ""
    public var do_you_want_to_change_the_hh = ""
    public var expected_hh_message = ""
    public var expected_hh_can_not_be_zero = ""
    public var expected_hh_can_not_be_zero_after_eb_upload = ""
    public var enter_remarks = ""
    public var locked_house = ""
    public var refused_answer = ""
    public var not_found = ""
    public var family_migrated = ""
    public var house_demolished = ""
    public var other = ""
    public var cancel = ""
    public var ok = ""
    public var enter_reson_to_skip_household = ""
    public var hh_member_details = ""
    public var add_member = ""
    public var refresh = ""
    public var name_of_person = ""
    public var relationship = ""
    public var sex = ""
    public var birth_address1 = ""
    public var birth_address2 = ""
    public var birth_address3 = ""
    public var birth_tehsil = ""
    public var birth_district = ""
    public var birth_state = ""
    public var current_house = ""
    public var current_village = ""
    public var current_pincode = ""
    public var current_state = ""
    public var current_district = ""
    public var current_sub_district = ""
    public var father_birth_address = ""
    public var father_birth_address2 = ""
    public var father_birth_address3 = ""
    public var mother_birth_address = ""
    public var mother_birth_address2 = ""
    public var mother_birth_address3 = ""
    public var place_of_last_residence = ""
    public var place_of_last_residence2 = ""
    public var place_of_last_residence3 = ""
    public var member_available = ""
    public var member_migrated = ""
    public var member_died = ""
    public var serial_number = ""
    public var available = ""
    public var dead = ""
    public var migrated_out = ""
    public var not_available = ""
    public var locked = ""
    public var new_ = ""
    public var signature_required = ""
    public var press_ok_to_take_signature = ""
    public var respondent_signature = ""
    public var enumerator_signature = ""
    public var sup_signature = ""
    public var signature_consent = ""
    public var respondant_unable_to_sign_consent = ""
    public var respondent = ""
    public var emulator_status = ""
    public var next = ""
    public var total_assigned_eb = ""
    public var uploaded_eb = ""
    public var pending_eb = ""
    public var current_eb_status = ""
    public var eb_number = ""
    public var household_status = ""
    public var total_original_household = ""
    public var total_available_households = ""
    public var total_migrated_hh = ""
    public var total_locked_hh = ""
    public var total_not_available_hh = ""
    public var total_new_hh = ""
    public var total_households_original_new = ""
    public var total_updated_households = ""
    public var total_pending_households = ""
    public var member_status = ""
    public var total_original_members = ""
    public var available_members = ""
    public var dead_member = ""
    public var migrated_member = ""
    public var total_new_members = ""
    public var total_updated_members = ""
    public var total_members_original_new = ""
    public var members_yet_to_be_udated = ""
    public var member_with_passport = ""
    public var member_with_aadhaar = ""
    public var members_with_mobile_number = ""
    public var member_with_voterID = ""
    public var member_with_dl = ""
    public var total_house_hold = ""
    public var total_old_hh = ""
    public var total_npr_member = ""
    public var total_updated_npr_member = ""
    public var member_with_pancard = ""
    public var na_member = ""
    public var loced_member = ""
    public var total_old_member = ""
    public var total_old_member_found = ""
    public var total_migrated_member = ""
    public var total_new_member = ""
    public var total_new_member_with_passport = ""
    public var total_new_member_with_aadhaar = ""
    public var total_new_member_with_voterID = ""
    public var total_new_member_with_dl = ""
    public var total_new_member_with_pancard = ""
    public var pending_members = ""
    public var total_members_found = ""
    public var choose_country = ""
    public var choose_state = ""
    public var choose_Nationality = ""
    public var choose_district = ""
    public var choose_tehsil = ""
    public var choose_respondant = ""
    public var yes = ""
    public var no = ""
    public var reload_master_directory = ""
    public var sup_remark_length = ""
    public var submit = ""
    public var button_save = ""
    public var button_update = ""
    public var button_add_member = ""
    public var hh_skipped = ""
    public var member_migrated_successfully = ""
    public var member_dead_successfully = ""
    public var are_you_sure = ""
    public var to_exit_from_app = ""
    public var alert = ""
    public var eb_completion_alert1 = ""
    public var eb_completion_alert2_title = ""
    public var eb_completion_alert2 = ""
    public var enumerator_sign = ""
    public var sup_sign = ""
    public var to_skip_hh = ""
    public var to_mark_member = ""
    public var as_migrated = ""
    public var as_dead = ""
    public var are_you_sure_to_exit_from_hh_form = ""
    public var due_to_locked = ""
    public var are_you_sure_to_exit = ""
    public var you_will_loss_data = ""
    public var user_does_not_exist = ""
    public var please_check_your_internet_connection = ""
    public var wrong_login_type = ""
    public var no_imei_or_logintype_passed = ""
    public var imei_exist = ""
    public var cancel_hit = ""
    public var verify_otp = ""
    public var otp_send_on = ""
    public var please_enter_correct_otp = ""
    public var selected_member_move_in_new_household = ""
    public var signin_sucess = ""
    public var signin_sucess_in_another_device = ""
    public var eb_not_alloted = ""
    public var upload_eb = ""
    public var uploaded = ""
    public var resend_otp_success = ""
    public var forgot_password = ""
    public var supervisor_login = ""
    public var registered_userId = ""
    public var new_password = ""
    public var retype_password = ""
    public var chnage_password_via_otp = ""
    public var CHANGE_PASSWORD = ""
    public var password_field_can_not_be_blank = ""
    public var both_password_should_be_same = ""
    public var password_chnaged = ""
    public var please_login_again = ""
    public var no_member_to_make_head = ""
    public var no_eb_to_choose_for_this_sup = ""
    public var do_you_want_to_upload_locked_hh_also1 = ""
    public var do_you_want_to_upload_locked_hh_also2 = ""
    public var eb_mark_as_completed = ""
    public var device_is_de_registered_so_not_allowed_yo_upload = ""
    public var validation_census_house_no = ""
    public var validation_census_house_no_zero = ""
    public var validation_new_census_household_no_zero = ""
    public var you_have_complted_10_hh_please_upload = ""
    public var you_have_complted_50_member_please_upload = ""
    public var validation_new_census_household_no = ""
    public var validation_name = ""
    public var validation_first_name = ""
    public var validation_first_name_startwith = ""
    public var validation_middle_name = ""
    public var validation_middle_name_startwith = ""
    public var validation_last_name = ""
    public var validation_last_name_startwith = ""
    public var validation_hh_no = ""
    public var validation_hh_no_already_exist = ""
    public var validation_newchh_no_already_exist = ""
    public var validation_hh_family_membr_no = ""
    public var validation_relationship = ""
    public var validation_nationality = ""
    public var feild_should_not = ""
    public var validation_gender = ""
    public var validation_marital_status = ""
    public var validation_member_dob = ""
    public var validation_member_dob_not_valid = ""
    public var validation_dob_date_today_date = ""
    public var validation_dob_date_future_date = ""
    public var validation_member_birthcountry = ""
    public var validation_member_birthstate = ""
    public var validation_member_birthdistrict = ""
    public var validation_member_Nationality = ""
    public var validation_member_birthtehsil = ""
    public var validation_education = ""
    public var validation_occupation = ""
    public var validation_present_state = ""
    public var validation_present_district = ""
    public var validation_present_sub_district = ""
    public var validation_present_address1 = ""
    public var validation_present_address2 = ""
    public var validation_present_pincode = ""
    public var validation_permaneent_country = ""
    public var validation_permaneent_state = ""
    public var validation_permaneent_district = ""
    public var validation_permaneent_tehsil = ""
    public var validation_permaneent_address1 = ""
    public var validation_permaneent_address2 = ""
    public var validation_permaneent_pincode = ""
    public var validation_staying_at_present_address_yes_no = ""
    public var validation_staying_at_present_address_years = ""
    public var validation_staying_at_present_address_years_can_not_be_more_than_age = ""
    public var validation_staying_at_present_address_years_invalid = ""
    public var validation_last_residence_country = ""
    public var validation_last_residence_state = ""
    public var validation_last_residence_district = ""
    public var validation_father_name = ""
    public var validation_father_dob = ""
    public var validation_father_dob_today_date = ""
    public var validation_father_dob_future_date = ""
    public var validation_mother_dob_not_valid = ""
    public var validation_father_dob_not_valid = ""
    public var validation_father_dob_with_member_same = ""
    public var validation_father_birth_country = ""
    public var validation_father_birth_state = ""
    public var validation_father_birth_district = ""
    public var validation_mother_name = ""
    public var validation_mother_dob = ""
    public var validation_mother_birth_country = ""
    public var validation_mother_birth_state = ""
    public var validation_mother_birth_district = ""
    public var validation_spouse_name = ""
    public var validation_aadhaar = ""
    public var validation_mobile = ""
    public var validation_passport = ""
    public var validation_voterid = ""
    public var validation_pan_card = ""
    public var validation_dl = ""
    public var validation_respondent_name = ""
    public var validation_respondent_mobile = ""
    public var validation_spouse_name_blank = ""
    public var data_clear_open_app_again = ""
    public var shift = ""
    public var to_shift = ""
    public var select_hh_for_member_shifting = ""
    public var choose_any_hh_to_shift_member = ""
    public var db_reload = ""
    public var selected_members_are = ""
    public var remaning_members = ""
    public var select_any_member_to_split = ""
    public var spliting_completed = ""
    public var one_member_should_be_available_to_split = ""
   // public var first_member_sr_no = ""
   // public var first_hh_no = ""
    public var failed_to_download_file_no_data_found = ""
    public var recovery = ""
    public var hh_type = ""
    public var normal = ""
    public var institutional = ""
    public var houseless = ""
    public var check_hh_type = ""
    public var name_of_institue = ""
    public var validation_name_of_institution = ""
    public var delete = ""
    public var to_delete = ""
    public var to_delete_hh = ""
    public var head_delete_message = ""
    public var member_deleted_sucess_message1 = ""
    public var member_deleted_sucess_message2 = ""
    public var self_enu_ref_no = ""
    public var enter_mother_tounge = ""
    public var validation_mother_tounge_1 = ""
   // public var other_mother_tongue = ""
    public var error_wile_connecting_to_server = ""
    public var connecting_to_server = ""
    public var downloading_required_data = ""
    public var activated_devic_title = ""
    public var same_device_already_activated = ""
    public var switch_eb = ""
    public var no_eb = ""
    public var language_error = ""
    public var select_ur_language = ""
    public var no_data = ""
    public var search_dob = ""
    public var search_aadhaar = ""
    public var search_name = ""
    public var search_head = ""
    public var search_mobile = ""
    public var enter_search_name = ""
    public var enter_search_dob = ""
    public var enter_search_aadhaar = ""
    public var enter_search_head = ""
    public var enter_search_mobile = ""
    public var select_any_option_to_search = ""
    public var search_head_name_from_hlo = ""
    public var aadhar_detail_alert = ""
    public var relationship_with_head = ""
    public var permanent_address_same_as_member = ""
    public var country = ""
    public var choose_member = ""
    public var de_enroll_message1 = ""
    public var de_enroll_message2 = ""
    public var census_housing_number = ""
    public var census_house_hold_number = ""
    public var search_for_mother_tongue = ""
    public var loading = ""
    public var field_should_not_be_blank = ""
    public var validation_age = ""
    public var user_not_enrolled_for_mobile_application = ""
    public var email_id_not_available = ""
    public var server_error = ""
    public var unauthorized_access = ""
    public var invalid_otp = ""
    public var required_resources_downloaded_successfully = ""
    public var cancel_lower = ""
    public var OK = ""
    public var restart = ""
    public var server_connection_issue = ""
    public var connection_failed_due_to = ""
    public var failed = ""
    public var mother_tongue_already_present = ""
    public var no_data_to_upload = ""
    public var initializing_please_wait = ""
    public var retry_upload = ""
    public var upload_from_previous_device = ""
    public var validation_both_password_length = ""
    public var already_marked_as_complted_and_uninhabited = ""
    public var already_marked_as_complted_and = ""
    public var nua = ""
    public var upd2 = ""
    public var upd1 = ""
    public var lat1 = ""
    public var update_downloaded = ""
    public var unauthorized_access_while_download_upload_data = ""
   // public var title_activity_sup_assigned_eb = ""
    public var date_of_birth_format_hint = ""
   // public var npr_toll_free_number = ""
    public var privacy_policy = ""
    public var faq = ""
    public var contact_us = ""
    public var terms_of_use = ""
    public var about_us = ""
    public var keyboard_settings = ""
    public var intro = ""
    public var retry = ""
    public var password_changed_message = ""
    public var view_edit_not_uploaded_message = ""
    public var view_edit_uploaded_list_message = ""
    public var invalid_selfenurefno = ""
    public var seconds_remaining = ""
    public var validation_name_special_char = ""
    public var got_it = ""
    public var clear_all_data = ""
    public var do_you_want_continue_selected_lang_title = ""
    public var do_you_want_continue_selected_lang_desc = ""

    public var relationship_to_head = [ModelNameID]()
    public var relationship_to_head_male = [ModelNameID]()
    public var relationship_to_head_female = [ModelNameID]()
//    public var relationship_to_head2 = [ModelNameID]()
//    public var relationship_to_head2_male = [ModelNameID]()
//    public var relationship_to_head2_female = [ModelNameID]()
    public var marital_statusArr = [ModelNameID]()
    public var education_qualification = [ModelNameID]()
    public var occupationArr = [ModelNameID]()
    
    public var mother_toungeArr = [ModelNameID]()
    
}

class LanguageListModel: Decodable {
    
    let langauges : [ModelNameID]
    
}
class ModelNameID: Codable {
    
    let  name, id: String?

        enum CodingKeys: String, CodingKey {
            
            case name, id
        }

        init(empty: String?, name: String?, id: String?) {
           
            self.name = name
            self.id = id
        }
    
}

class RelationshipToHead: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
        
    }
    
}
class RelationshipToHeadMale: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
        
    }
    
}
class RelationshipToHeadFemale: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
    }
    
}

class RelationshipToHead2: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
    }
    
}
class RelationshipToHead2Male: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
    }
    
}
class RelationshipToHead2Female: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
    }
    
}
class MaritalStatus: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
    }
    
}
class Education_Qualification: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
    }
    
}
class Occupation: Codable {
    
    let id, name: String
    init(id: String, name: String) {
        self.name = name
        self.id = id
    }
    
}
